Repository opensearch-project/dashboards-observability, pull requests merged in 2023-06, with the labels that each got.

#472 1.3.10 Release Notes
  release-notes/dashboards-observability.release-notes-1.3.10.md
Labels: backport main

#515 Correct release note name
  release-notes/dashboards-observability.release-notes-2.8.0.0.md
Labels: backport 2.x

#565 Merge Kibana backend from osints/dev into main
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/__test__/kibana_backend.test.ts
  server/adaptors/integrations/integrations_builder.ts
  server/adaptors/integrations/integrations_kibana_backend.ts
  server/adaptors/integrations/types.ts
  server/adaptors/integrations/validators.ts
  server/plugin.ts
  server/routes/integrations/__tests__/integrations_router.test.ts
  server/routes/integrations/integrations_router.ts
Labels: enhancement

#588 Feature/prerelease code cleanup
  public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/shared_components.test.tsx
  public/components/event_analytics/explorer/visualizations/shared_components/plotly_viz_editor/index.tsx
  public/components/event_analytics/explorer/visualizations/visualization_specs/default_spec.ts
  public/components/visualizations/assets/__tests__/__snapshots__/assets.test.tsx.snap
  public/components/visualizations/assets/__tests__/assets.test.tsx
  public/components/visualizations/assets/chart_bar.tsx
  public/components/visualizations/assets/chart_bar_horizontal.tsx
  public/components/visualizations/assets/chart_datatable.tsx
  public/components/visualizations/assets/chart_line.tsx
  public/components/visualizations/assets/chart_pie.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/gauge.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/metrics.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/text.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap
  public/components/visualizations/charts/bar/bar_type.ts
  public/components/visualizations/charts/bubble/bubble_type.ts
  public/components/visualizations/charts/data_table/data_table_type.ts
  public/components/visualizations/charts/financial/gauge/gauge_type.ts
  public/components/visualizations/charts/lines/line_type.ts
  public/components/visualizations/charts/maps/heatmap.tsx
  public/components/visualizations/charts/maps/heatmap_type.ts
  public/components/visualizations/charts/maps/treemap_type.ts
  public/components/visualizations/charts/metrics/metrics_type.ts
  public/components/visualizations/charts/pie/pie_type.ts
  public/components/visualizations/charts/text/text_type.ts
Labels: backport 1.x, backport 2.x, backport 2.5, backport 2.6, backport 1.3, backport 2.7, backport 2.8

#589 Feature/prerelease code cleanup
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel_footer.tsx
  public/components/event_analytics/explorer/visualizations/shared_components/empty_placeholder.scss
  public/components/event_analytics/explorer/visualizations/shared_components/empty_placeholder.tsx
  public/components/event_analytics/explorer/visualizations/shared_components/index.ts
  public/components/event_analytics/explorer/visualizations/shared_components/vis_canvass_placeholder.tsx
  public/components/event_analytics/explorer/visualizations/workspace_panel/workspace_panel.scss
  public/components/event_analytics/explorer/visualizations/workspace_panel/workspace_panel.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/gauge.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/metrics.test.tsx.snap
  public/components/visualizations/visualization.tsx
Labels: backport 2.x, backport 2.7, backport 2.8
