Repository opensearch-project/dashboards-observability, pull requests merged in 2023-01, with the labels that each got.

#174 Fix event analytics field blank margin
  public/components/visualizations/charts/logs_view/logs_view.scss
Labels: backport 1.x, backport 2.x

#158 Update 2.x to be the same as observability repo
  release-notes/opensearch-observability.release-notes-2.4.1.0.md
Labels: backport main

#179 Fixed PPL Error in containers & added tool tip to date picker
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx
  public/components/metrics/view/__tests__/metrics_grid.test.tsx
Labels: backport main, backport 2.5

#190 Add release notes for 2.5
  release-notes/opensearch-observability.release-notes-2.5.0.0.md
Labels: backport 2.5

#202 Temporarily hide reporting context menu in notebooks
  public/components/notebooks/components/notebook.tsx
Labels: backport 2.x, backport main
