Repository opensearch-project/dashboards-observability, pull requests merged in 2023-09, with the labels that each got.

#964 Update search bar snapshots according to upstream changes
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/common/live_tail/__tests__/__snapshots__/live_tail_button.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/__tests__/__snapshots__/empty_panel.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/__tests__/__snapshots__/searchbar.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
Labels: backport 2.x

#969 Upgrade cypress/requests from 2 to 3
  .cypress/.DS_Store
  package.json
  yarn.lock
Labels: backport 2.x, maintenance

#956 Refactor add_integration_flyout to break out nested methods
  public/components/integrations/components/__tests__/__snapshots__/added_integration_flyout.test.tsx.snap
  public/components/integrations/components/__tests__/added_integration_flyout.test.tsx
  public/components/integrations/components/__tests__/mapping_validation.test.ts
  public/components/integrations/components/add_integration_flyout.tsx
Labels: integrations, maintenance

#978 Release Notes 2.10
  release-notes/dashboards-observability.release-notes-2.10.0.0.md
Labels: backport 2.x, backport main

#1009 Create React component for Integrations Setup UI
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/setup_integration.test.tsx
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/home.tsx
Labels: enhancement, backport 2.x, integrations
