Repository opensearch-project/dashboards-observability, pull requests merged in 2023-02, with the labels that each got.

#197 fix a few bugs with respect to refreshes and mode set via session sto…
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
Labels: backport 2.x, backport main

#152 Add new page/route for notebooks create and rename
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/note_table.test.tsx
  public/components/notebooks/components/main.tsx
  public/components/notebooks/components/note_table.tsx
Labels: backport 2.x, v2.6.0

#247 Update error handling in viz container
  common/types/custom_panels.ts
  public/components/custom_panels/custom_panel_view.tsx
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.scss
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.scss
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx
  yarn.lock
Labels: backport 2.x, backport main

#251 Panels filter check for where clause
  common/constants/shared.ts
  public/components/custom_panels/helpers/utils.tsx
Labels: backport 2.x

#248 [Bug Bash Fixes][Event Analytics] some fixes
  common/constants/explorer.ts
  common/constants/shared.ts
  public/components/common/search/search.tsx
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
  public/components/event_analytics/explorer/events_views/__tests__/__snapshots__/doc_viewer.test.tsx.snap
  public/components/event_analytics/explorer/events_views/__tests__/__snapshots__/doc_viewer_row.test.tsx.snap
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/log_explorer.tsx
  public/components/event_analytics/explorer/save_panel/save_panel.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.scss
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
  public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_availability.tsx
  public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx
  public/components/event_analytics/explorer/visualizations/index.tsx
  public/components/event_analytics/home/home.tsx
  public/components/metrics/sidebar/sidebar.scss
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/logs_view.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/charts/bar/bar.tsx
  public/components/visualizations/charts/lines/line.tsx
  public/components/visualizations/charts/pie/pie.tsx
  public/components/visualizations/visualization.tsx
  public/framework/redux/store/shared_state.ts
Labels: backport 2.x, backport 2.5

#258 Remove timeseries data validation to get back line chart support
  public/components/visualizations/visualization.tsx
Labels: backport 2.x, backport 2.5

#270 quick fix for traces and services indiviudal page
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
Labels: backport 2.x, backport 2.5

#265 fix up cypress and add jaeger tests
  .cypress/integration/4_trace_analytics_dashboard.spec.js
  .cypress/integration/5_trace_analytics_services.spec.js
  .cypress/integration/6_trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filters.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap
  public/components/trace_analytics/components/dashboard/mode_picker.tsx
  public/components/trace_analytics/components/dashboard/top_groups_page.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/services_table.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/service_breakdown_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
  public/components/trace_analytics/home.tsx
Labels: backport 2.x, backport 2.5

#244 Operational panels cypress fix
  .cypress/integration/3_panels.spec.js
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/custom_panel_table.tsx
  public/components/custom_panels/custom_panel_view.tsx
  public/components/custom_panels/helpers/add_visualization_popover.tsx
  public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
Labels: backport 2.x

#229 Add reporting on-demand menu items back in notebooks
  .gitignore
  public/components/notebooks/components/helpers/__tests__/reporting_context_menu_helper.test.tsx
  public/components/notebooks/components/helpers/reporting_context_menu_helper.tsx
  public/components/notebooks/components/notebook.tsx
Labels: backport 2.x

#282 fix bug for failed notebook create
  public/components/notebooks/components/main.tsx
Labels: backport 2.x

#295 Fix Node.js and Yarn installation in CI
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
Labels: backport 2.x

#309 move performance now to run time dep
  package.json
  release-notes/opensearch-observability.release-notes-2.6.0.0.md
Labels: backport 2.x, backport main

#277 [Refactoring] Redux and log pattern related refactoring
  common/constants/explorer.ts
  public/components/app.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_header.test.tsx.snap
  public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_table.test.tsx.snap
  public/components/event_analytics/explorer/log_patterns/__tests__/patterns_header.test.tsx
  public/components/event_analytics/explorer/log_patterns/__tests__/patterns_table.test.tsx
  public/components/event_analytics/explorer/log_patterns/log_patterns.tsx
  public/components/event_analytics/explorer/log_patterns/patterns_header.tsx
  public/components/event_analytics/explorer/log_patterns/patterns_table.tsx
  public/components/event_analytics/home/home.tsx
  public/components/event_analytics/redux/reducers/fetch_reducers.ts
  public/components/event_analytics/redux/slices/count_distribution_slice.ts
  public/components/event_analytics/redux/slices/field_slice.ts
  public/components/event_analytics/redux/slices/patterns_slice.ts
  public/components/event_analytics/redux/slices/query_result_slice.ts
  public/components/event_analytics/redux/slices/query_slice.ts
  public/components/event_analytics/redux/slices/query_tab_slice.ts
  public/components/event_analytics/redux/slices/visualization_slice.ts
  public/components/event_analytics/redux/slices/viualization_config_slice.ts
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/__tests__/searchbar.test.tsx
  public/components/metrics/sidebar/__tests__/sidebar.test.tsx
  public/components/metrics/top_menu/__tests__/metrics_export_panel.test.tsx
  public/components/metrics/top_menu/__tests__/top_menu.test.tsx
  public/components/metrics/view/__tests__/metrics_grid.test.tsx
  public/framework/redux/reducers/index.ts
  public/framework/redux/store/index.ts
Labels: backport 2.x
