Repository opensearch-project/dashboards-observability, pull requests merged in 2023-07, with the labels that each got.

#601 Resolve heatmap issue and update snapshots
  public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/shared_components.test.tsx
  public/components/event_analytics/explorer/visualizations/shared_components/plotly_viz_editor/index.tsx
  public/components/event_analytics/explorer/visualizations/visualization_specs/default_spec.ts
  public/components/visualizations/assets/__tests__/__snapshots__/assets.test.tsx.snap
  public/components/visualizations/assets/__tests__/assets.test.tsx
  public/components/visualizations/assets/chart_bar.tsx
  public/components/visualizations/assets/chart_bar_horizontal.tsx
  public/components/visualizations/assets/chart_datatable.tsx
  public/components/visualizations/assets/chart_line.tsx
  public/components/visualizations/assets/chart_pie.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/gauge.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/logs_view.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/metrics.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/text.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap
  public/components/visualizations/charts/bar/bar_type.ts
  public/components/visualizations/charts/bubble/bubble_type.ts
  public/components/visualizations/charts/data_table/data_table_type.ts
  public/components/visualizations/charts/financial/gauge/gauge_type.ts
  public/components/visualizations/charts/lines/line_type.ts
  public/components/visualizations/charts/logs_view/logs_view_type.ts
  public/components/visualizations/charts/maps/heatmap_type.ts
  public/components/visualizations/charts/maps/treemap_type.ts
  public/components/visualizations/charts/metrics/metrics_type.ts
  public/components/visualizations/charts/pie/pie_type.ts
  public/components/visualizations/charts/text/text_type.ts
Labels: backport 2.3, backport 2.2, backport 2.1, backport 2.0

#608 Update tests and snapshots
  public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/shared_components.test.tsx
  public/components/visualizations/assets/__tests__/__snapshots__/assets.test.tsx.snap
  public/components/visualizations/assets/__tests__/assets.test.tsx
  public/components/visualizations/assets/chart_bar.tsx
  public/components/visualizations/assets/chart_bar_horizontal.tsx
  public/components/visualizations/assets/chart_datatable.tsx
  public/components/visualizations/assets/chart_line.tsx
  public/components/visualizations/assets/chart_pie.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/data_table.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/text.test.tsx.snap
  public/components/visualizations/charts/bar/bar_type.ts
  public/components/visualizations/charts/bar/horizontal_bar_type.ts
  public/components/visualizations/charts/bubble/bubble_type.ts
  public/components/visualizations/charts/data_table/data_table_type.ts
  public/components/visualizations/charts/financial/candle_stick/candle_stick_type.ts
  public/components/visualizations/charts/financial/gauge/gauge_type.ts
  public/components/visualizations/charts/histogram/histogram_type.ts
  public/components/visualizations/charts/lines/line_type.ts
  public/components/visualizations/charts/maps/heatmap_type.ts
  public/components/visualizations/charts/maps/treemap_type.ts
  public/components/visualizations/charts/pie/pie_type.ts
  public/components/visualizations/charts/text/text_type.ts
Labels: backport 1.x, backport 1.3, backport 2.2, backport 2.1, backport 2.0

#612 Update tests and snapshots
  public/components/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/explorer/visualizations/shared_components/__tests__/shared_components.test.tsx
  public/components/visualizations/assets/__tests__/__snapshots__/assets.test.tsx.snap
  public/components/visualizations/assets/__tests__/assets.test.tsx
  public/components/visualizations/assets/chart_bar.tsx
  public/components/visualizations/assets/chart_bar_horizontal.tsx
  public/components/visualizations/assets/chart_datatable.tsx
  public/components/visualizations/assets/chart_line.tsx
  public/components/visualizations/assets/chart_pie.tsx
  public/components/visualizations/charts/bar/bar_type.ts
  public/components/visualizations/charts/bar/horizontal_bar_type.ts
  public/components/visualizations/charts/bubble/bubble_type.ts
  public/components/visualizations/charts/data_table/data_table_type.ts
  public/components/visualizations/charts/financial/candle_stick/candle_stick_type.ts
  public/components/visualizations/charts/financial/gauge/gauge_type.ts
  public/components/visualizations/charts/histogram/histogram_type.ts
  public/components/visualizations/charts/lines/line_type.ts
  public/components/visualizations/charts/maps/heatmap_type.ts
  public/components/visualizations/charts/maps/treemap_type.ts
  public/components/visualizations/charts/pie/pie_type.ts
  public/components/visualizations/charts/text/text_type.ts
Labels: backport 1.3

#619 Upgrade tough-cookie and semver
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.9

#627 Upgrade tough-cookie and semver (#619)
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.9

#650 Remove unused files
  public/components/explorer/visualizations/__tests__/__snapshots__/datapanel.test.tsx.snap
  public/components/explorer/visualizations/__tests__/__snapshots__/field_accordion.test.tsx.snap
  public/components/explorer/visualizations/__tests__/__snapshots__/field_item.test.tsx.snap
  public/components/explorer/visualizations/__tests__/__snapshots__/field_list.test.tsx.snap
  public/components/explorer/visualizations/__tests__/__snapshots__/lens_field_icon.test.tsx.snap
  public/components/explorer/visualizations/__tests__/datapanel.test.tsx
  public/components/explorer/visualizations/__tests__/field_accordion.test.tsx
  public/components/explorer/visualizations/__tests__/field_item.test.tsx
  public/components/explorer/visualizations/__tests__/field_list.test.tsx
  public/components/explorer/visualizations/__tests__/lens_field_icon.test.tsx
  public/components/explorer/visualizations/_mixins.scss
  public/components/explorer/visualizations/_variables.scss
  public/components/explorer/visualizations/app.scss
  public/components/explorer/visualizations/config_panel/config_panel.scss
  public/components/explorer/visualizations/config_panel/config_panel.tsx
  public/components/explorer/visualizations/datapanel.scss
  public/components/explorer/visualizations/datapanel.tsx
  public/components/explorer/visualizations/drag_drop/drag_drop.scss
  public/components/explorer/visualizations/drag_drop/drag_drop.tsx
  public/components/explorer/visualizations/drag_drop/index.ts
  public/components/explorer/visualizations/drag_drop/providers.tsx
  public/components/explorer/visualizations/drag_drop/readme.md
  public/components/explorer/visualizations/fieldList.tsx
  public/components/explorer/visualizations/field_item.scss
  public/components/explorer/visualizations/field_item.tsx
  public/components/explorer/visualizations/field_list.scss
  public/components/explorer/visualizations/fields_accordion.tsx
  public/components/explorer/visualizations/frame_layout.scss
  public/components/explorer/visualizations/frame_layout.tsx
  public/components/explorer/visualizations/lens_field_icon.tsx
  public/components/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/explorer/visualizations/shared_components/__tests__/shared_components.test.tsx
  public/components/explorer/visualizations/shared_components/empty_placeholder.tsx
  public/components/explorer/visualizations/shared_components/index.ts
  public/components/explorer/visualizations/shared_components/toolbar_button.scss
  public/components/explorer/visualizations/shared_components/toolbar_button.tsx
  public/components/explorer/visualizations/workspace_panel/chart_switch.scss
  public/components/explorer/visualizations/workspace_panel/chart_switch.tsx
Labels: backport 1.x

#653 remove unused files and update snapshots
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/common/live_tail/__tests__/__snapshots__/live_tail_button.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/__tests__/__snapshots__/empty_panel.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap
  public/components/event_analytics/__tests__/__snapshots__/no_results.test.tsx.snap
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
  public/components/event_analytics/explorer/events_views/__tests__/__snapshots__/doc_viewer.test.tsx.snap
  public/components/event_analytics/explorer/events_views/__tests__/__snapshots__/doc_viewer_row.test.tsx.snap
  public/components/event_analytics/explorer/events_views/json_code_block/__tests__/__snapshots__/json_code_block.test.tsx.snap
  public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/event_analytics/explorer/timechart_header/__tests__/__snapshots__/timechart_header.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/_mixins.scss
  public/components/event_analytics/explorer/visualizations/_variables.scss
  public/components/event_analytics/explorer/visualizations/app.scss
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel.scss
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
  public/components/event_analytics/explorer/visualizations/count_distribution/__tests__/__snapshots__/count_distribution.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/empty_placeholder.tsx
  public/components/event_analytics/explorer/visualizations/shared_components/toolbar_button.scss
  public/components/event_analytics/explorer/visualizations/shared_components/toolbar_button.tsx
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_input.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_query_grid.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_edit_popover.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/latency_trend_cell.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_flyout.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/data_table.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/plotly/__tests__/__snapshots__/plotly.test.tsx.snap
Labels: backport 2.2, backport 2.1, backport 2.0

#662 Remove unused files
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/__snapshots__/shared_components.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/shared_components/__tests__/shared_components.test.tsx
  public/components/event_analytics/explorer/visualizations/shared_components/index.ts
  public/components/event_analytics/explorer/visualizations/shared_components/toolbar_button.scss
  public/components/event_analytics/explorer/visualizations/shared_components/toolbar_button.tsx
  public/components/event_analytics/index.scss
Labels: backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.4

#724 fix name change bug and modify test to test behavior
  .cypress/integration/9_integrations.spec.js
  public/components/integrations/components/add_integration_flyout.tsx
Labels: backport 2.x, backport 2.9

#727 Search bar fixes
  .cypress/integration/9_integrations.spec.js
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/integration_assets_panel.tsx
Labels: backport 2.x, backport 2.9

#740 Update vpc readme & references
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/info/README.md
  server/adaptors/integrations/__data__/repository/nginx/info/README.md
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.1.json
Labels: backport 2.x, integration, backport 2.9
