Repository opensearch-project/dashboards-observability, pull requests merged in 2023-10, with the labels that each got.

#1085 Finish frontend S3 framework for integrations
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/setup_integration.tsx
Labels: backport 2.x, integrations, ux-integration, backport 2.11

#1090 Data sources copy updates
  common/constants/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/connection_details.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_description.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap
  public/components/datasources/components/data_connections_header.tsx
  public/components/datasources/components/manage/access_control_tab.tsx
  public/components/datasources/components/manage/connection_management_callout.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/manage_data_connections_description.tsx
  public/components/datasources/components/new/auth_details.tsx
  public/components/datasources/components/new/configure_datasource.tsx
  public/components/datasources/components/new/configure_prometheus_datasource.tsx
  public/components/datasources/components/new/configure_s3_datasource.tsx
  public/components/datasources/components/new/new_datasource_card_view.tsx
  public/components/datasources/components/new/query_permissions.tsx
  public/components/datasources/components/new/review_prometheus_datasource_configuration.tsx
  public/components/datasources/components/new/review_s3_datasource_configuration.tsx
Labels: backport 2.x, backport 2.11

#1096 Explorer minor UI updates
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/common/search/autocomplete.tsx
  public/components/common/search/search.scss
  public/components/common/search/search.tsx
  public/components/common/search/sql_search.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/components/event_analytics/explorer/explorer.scss
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/sidebar.tsx
  public/components/event_analytics/explorer/visualizations/direct_query_vis.tsx
  public/components/event_analytics/redux/slices/query_slice.ts
Labels: backport 2.x, backport 2.11

#1101 Reverting notebooks changes, add docs/validation to datasources, explorer minor fixes
  common/constants/data_connections.ts
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap
  public/components/datasources/components/new/configure_datasource.tsx
  public/components/datasources/components/new/configure_prometheus_datasource.tsx
  public/components/datasources/components/new/configure_s3_datasource.tsx
  public/components/datasources/components/new/name_row.tsx
  public/components/datasources/components/new/query_permissions.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/events_views/docViewRow.tsx
  public/components/event_analytics/explorer/events_views/surrounding_flyout.tsx
  public/components/event_analytics/utils/utils.tsx
  public/components/notebooks/components/helpers/__tests__/sampleZeppelinNotebooks.tsx
  public/components/notebooks/components/helpers/__tests__/zeppelin_parser.test.tsx
  public/components/notebooks/components/helpers/default_parser.tsx
  public/components/notebooks/components/helpers/zeppelin_parser.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/notebooks/components/paragraph_components/para_output.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
  public/components/notebooks/index.scss
Labels: backport 2.x, backport 2.11

#1114 Fix dropdown display behavior
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/setup_integration.tsx
Labels: backport 2.x, backport 2.11

#1110 Remove integrations card from datasources
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/new/configure_s3_datasource.tsx
  public/components/datasources/components/new/new_datasource_card_view.tsx
Labels: backport 2.x, backport 2.11

#1121 Remove PPL keyword from general placeholder in search bar
  public/components/common/search/autocomplete.tsx
Labels: backport 2.x, backport 2.11

#1124 Placeholder change related test fixes
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/common/search/autocomplete.test.tsx
Labels: backport 2.x, backport 2.11

#1130 2.11 release notes
  release-notes/dashboards-observability.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#1143 Allow patch on allowedRoles
  common/constants/shared.ts
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/manage/access_control_tab.tsx
  public/components/datasources/components/new/configure_datasource.tsx
  public/components/datasources/components/new/query_permissions.tsx
  server/adaptors/ppl_plugin.ts
  server/routes/data_connections/data_connections_router.ts
Labels: backport 2.x, backport 2.11

#1170 Fix events home table and toast life time
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/event_analytics/home/saved_objects_table.tsx
  public/components/event_analytics/index.tsx
Labels: backport 2.x, backport main

#1169 Fixed Visualization Config Panel dark mode
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel.scss
Labels: backport 2.x, backport 2.11

#1177 Support cancellation of async queries
  public/components/common/search/sql_search.tsx
  public/components/event_analytics/explorer/direct_query_running.tsx
  public/components/event_analytics/redux/slices/search_meta_data_slice.ts
  public/services/requests/sql.ts
  server/adaptors/opensearch_observability_plugin.ts
  server/routes/datasources/datasources_router.ts
Labels: backport 2.x, backport 2.11

#1187 Bug fixes for observability count distribution and application analytics
  public/components/common/query_utils/index.ts
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/visualizations/count_distribution/count_distribution.tsx
  public/components/event_analytics/redux/slices/count_distribution_slice.ts
Labels: backport 2.x, backport 2.11

#1192 Remove husky pre-commit checks
  .husky/.gitignore
  .husky/pre-commit
  package.json
Labels: backport 2.11

#1150 Add integrations queries for Flint
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/create_integration_helpers.ts
  public/components/integrations/components/setup_integration.tsx
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_elb/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_elb/assets/refresh_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: backport 2.x, backport 2.11

#1196 Correct query schema for ELB mview generation
  public/services/requests/sql.ts
  server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql
Labels: backport 2.x, backport 2.11

#1197 [Explorer] Fixes for cancel button and saved object loading
  common/constants/data_sources.ts
  public/components/common/search/sql_search.tsx
  public/components/event_analytics/explorer/direct_query_running.tsx
  public/components/event_analytics/home/home.tsx
  public/services/saved_objects/saved_object_loaders/explorer_saved_object_loader.ts
Labels: backport 2.x, backport 2.11

#1208 Saved object datasource backward compatibility fixes
  public/components/common/search/sql_search.tsx
  public/services/saved_objects/saved_object_loaders/explorer_saved_object_loader.ts
Labels: backport 2.x, backport 2.11

#1205 disabling inspect and default pattern/timestamp buttons when using async data sources
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/field.test.tsx
  public/components/event_analytics/explorer/sidebar/__tests__/sidebar.test.tsx
  public/components/event_analytics/explorer/sidebar/field.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.tsx
Labels: backport 2.x, backport 2.11

#1214 Add S3 integration for Nginx and VPC
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_mv_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_table_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/refresh_mv_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/assets/refresh_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: backport 2.x, backport 2.11

#1217 Update empty allowed roles to admin only
  public/components/datasources/components/new/query_permissions.tsx
Labels: backport 2.x, backport 2.11
