Repository opensearch-project/dashboards-observability, pull requests merged in 2023-04, with the labels that each got.

#386 Metrics analytics support for SOpanels
  .cypress/integration/2_notebooks.spec.js
  public/components/metrics/helpers/utils.tsx
  public/components/metrics/top_menu/__tests__/metrics_export_panel.test.tsx
  public/components/metrics/top_menu/metrics_export_panel.tsx
  public/components/metrics/top_menu/top_menu.tsx
Labels: backport 2.x, backport 2.7

#389 change plugin ordering
  public/plugin.ts
Labels: backport 2.x, backport 2.7

#392 notebooks fix for cypress and minor bugs
  .cypress/integration/2_notebooks.spec.js
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/main.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
Labels: backport 2.x, backport 2.7

#391 Update traces integration tests
  .cypress/integration/4_trace_analytics_dashboard.spec.js
  .cypress/integration/5_trace_analytics_services.spec.js
  .cypress/integration/6_trace_analytics_traces.spec.js
Labels: backport 2.x, backport 2.7

#398 Adjust metrics top menu layout to avoid overflow
  public/components/metrics/sidebar/__tests__/__snapshots__/searchbar.test.tsx.snap
  public/components/metrics/sidebar/search_bar.tsx
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/metrics/top_menu/top_menu.scss
  public/components/metrics/top_menu/top_menu.tsx
Labels: backport 2.7

#399 Fix redirection to legacy event_analytics URL from dashboards
  public/components/custom_panels/helpers/add_visualization_popover.tsx
Labels: backport 2.7

#401 Fix panel visualization preview & new viz workflow
  public/components/custom_panels/custom_panel_view_so.tsx
  public/components/custom_panels/home.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx
Labels: backport 2.7

#400 Support duplicate visualization in dashboard
  public/components/custom_panels/custom_panel_view_so.tsx
Labels: backport 2.7

#407 Fix saving multiple metrics to SOpanels
  public/components/custom_panels/helpers/add_visualization_helper.ts
  public/components/custom_panels/redux/panel_slice.ts
  public/components/metrics/top_menu/top_menu.tsx
Labels: backport 2.7

#416 [Dashboard listing] update edit url and view url
  .cypress/integration/3_panels.spec.ts
  public/components/custom_panels/custom_panel_view_so.tsx
  public/components/trace_analytics/requests/dashboard_request_handler.ts
  public/plugin.ts
  public/services/saved_objects/saved_object_savers/ppl/save_as_new_query.ts
Labels: backport 2.x, v2.7.0, backport 2.7

#427 change samples to saved object
  common/constants/custom_panels.ts
  public/components/custom_panels/home.tsx
  public/components/custom_panels/redux/panel_slice.ts
  server/adaptors/custom_panels/custom_panel_adaptor.ts
  server/common/helpers/custom_panels/sample_panels.ts
Labels: backport 2.x, backport 2.7
