Repository opensearch-project/dashboards-observability, pull requests merged in 2023-11, with the labels that each got.

#1223 Onboard prod jenkins docker images to github actions
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/dco.yml
Labels: enhancement, backport 2.x

#1225 [Backport 2.x] Onboard prod jenkins docker images to github actions
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/dco.yml
Labels: enhancement

#1226 Remove manual refresh for S3 integrations
  public/components/integrations/components/setup_integration.tsx
  server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_elb/assets/refresh_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_mv_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/refresh_mv_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/assets/refresh_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: backport 2.x, backport 2.11

#1239 Refactor repository reading for recursive directory searching
  server/adaptors/integrations/__test__/local_repository.test.ts
  server/adaptors/integrations/__test__/manager.test.ts
  server/adaptors/integrations/integrations_manager.ts
  server/adaptors/integrations/repository/__test__/repository.test.ts
  server/adaptors/integrations/repository/fs_data_adaptor.ts
  server/adaptors/integrations/repository/repository.ts
Labels: integrations, maintenance

#1250 Added following visualizations in nginx log overview dashboard
  server/adaptors/integrations/__data__/repository/nginx/assets/nginx-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/nginx/info/README.md
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/static/dashboard2.png
Labels: backport 2.x, integrations

#1234 Fix integration child mapping validation bug
  public/components/integrations/components/__tests__/mapping_validation.test.ts
  public/components/integrations/components/add_integration_flyout.tsx
Labels: bug, integrations

#1258 Ignore Antlr output in codecov
  codecov.yml
Labels: infrastructure

#1269 Remove overriding style on the height of option list
  public/components/event_analytics/explorer/visualizations/config_panel/config_panel.scss
Labels: backport 2.x, backport 2.11
