Repository opensearch-project/dashboards-observability, pull requests merged in 2023-05, with the labels that each got.

#441 Add Error handling on duplicate dashboard names
  public/components/custom_panels/custom_panel_table.tsx
  public/components/custom_panels/custom_panel_view_so.tsx
  public/components/custom_panels/redux/panel_slice.ts
Labels: backport 2.x, backport main

#449 Fix timestamp overriding issue
  public/components/event_analytics/explorer/explorer.tsx
  public/services/data_fetchers/ppl/ppl_data_fetcher.ts
Labels: backport main

#450 Renaming custom panels to Observability Dashboards
  .cypress/integration/3_panels.spec.ts
  .cypress/integration/7_app_analytics.spec.js
  README.md
  public/components/application_analytics/home.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/custom_panel_table.tsx
  public/components/custom_panels/custom_panel_view.tsx
  public/components/custom_panels/custom_panel_view_so.tsx
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx
  public/components/custom_panels/redux/panel_slice.ts
  test/panels_constants.tsx
Labels: backport main

#452 Fix delete failure when no osd item selected
  public/services/saved_objects/saved_object_client/saved_objects_actions.ts
Labels: backport main

#444 Open log patterns by default
  public/components/event_analytics/explorer/log_patterns/log_patterns.tsx
Labels: backport 2.x, backport 2.7

#494 Updating trace DSL request handler
  public/components/trace_analytics/requests/request_handler.ts
Labels: backport 2.x, backport 2.8

#488 Remove styling causing issue for banner in advanced settings
  public/components/event_analytics/explorer/explorer.scss
  public/components/metrics/index.scss
Labels: backport 2.x, backport 2.8

#491 Add Metrics cypress and bug fixes
  .cypress/integration/8_metrics_analytics.spec.js
  .cypress/utils/metrics_constants.js
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap
  public/components/event_analytics/explorer/save_panel/save_panel.tsx
  public/components/metrics/index.tsx
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/__tests__/__snapshots__/searchbar.test.tsx.snap
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/metrics_accordion.tsx
  public/components/metrics/sidebar/search_bar.tsx
  public/components/metrics/sidebar/sidebar.tsx
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/metrics/top_menu/top_menu.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/metrics/view/__tests__/metrics_grid.test.tsx
  public/components/metrics/view/metrics_grid.tsx
Labels: backport 2.x, backport 2.8

#506 2.8 release notes
  release-notes/opensearch-observability.release-notes-2.8.0.0.md
Labels: backport 2.x, backport 2.8
