Repository opensearch-project/dashboards-observability, pull requests merged in 2023-12, with the labels that each got.

#1280 Add a codecov directory fix to the config
  codecov.yml
Labels: maintenance

#1290 [CI/CD] Refactor Cypress Workflow
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/integration/datasources_test/datasources.spec.js
  .cypress/integration/event_analytics_test/event_analytics.spec.js
  .cypress/integration/integrations_test/integrations.spec.js
  .cypress/integration/metrics_analytics_test/metrics_analytics.spec.js
  .cypress/integration/notebooks_test/notebooks.spec.js
  .cypress/integration/panels_test/panels.spec.ts
  .cypress/integration/trace_analytics_test/trace_analytics_dashboard.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .github/workflows/integration-tests-workflow.yml
  package.json
Labels: infrastructure

#1312 Fix for Notebook Observability Visualization loading
  public/components/common/query_utils/index.ts
  public/components/custom_panels/helpers/utils.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/para_output.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: backport main

#1327 Correct date pass-through on Notebook Visualizations.
  public/components/common/query_utils/__tests__/query_utils.test.tsx
  public/components/common/query_utils/index.ts
  public/components/event_analytics/explorer/events_views/data_grid.scss
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/para_output.test.tsx
  public/components/notebooks/components/paragraph_components/para_output.tsx
Labels: backport main

#1292 Add enforce-labels action
  .github/draft-release-notes-config.yml
  .github/workflows/enforce-labels.yml
Labels: backport 2.x, infrastructure
