Repository opensearch-project/dashboards-observability, pull requests merged in 2024-05, with the labels that each got.

#1752 MDS Support for trace analytics
  opensearch_dashboards.json
  public/components/app.tsx
  public/components/application_analytics/components/config_components/service_config.tsx
  public/components/application_analytics/components/flyout_components/service_detail_flyout.tsx
  public/components/index.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/dashboard.test.tsx
  public/components/trace_analytics/components/dashboard/dashboard.tsx
  public/components/trace_analytics/components/dashboard/dashboard_content.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/service_view.test.tsx
  public/components/trace_analytics/components/services/__tests__/services.test.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/trace_view.test.tsx
  public/components/trace_analytics/components/traces/__tests__/traces.test.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/requests/dashboard_request_handler.ts
  public/components/trace_analytics/requests/request_handler.ts
  public/components/trace_analytics/requests/services_request_handler.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
  public/framework/core_refs.ts
  public/plugin.tsx
  public/types.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/trace_analytics_dsl_router.ts
Labels: enhancement, backport 2.x

#1739 added fix for jobs and cache Support for workbench ,MDS support
  common/types/data_connections.ts
  common/utils/shared.ts
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_databases.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/query_visual_editor.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/generate_fields.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/skipping_index_builder.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/hooks/use_polling.ts
  public/framework/catalog_cache/cache_loader.test.tsx
  public/framework/catalog_cache/cache_loader.tsx
  public/framework/catalog_cache/cache_manager.test.tsx
  public/framework/catalog_cache/cache_manager.ts
  public/framework/datasources/direct_query_hook.tsx
  public/plugin.tsx
  public/services/requests/sql.ts
  public/types.ts
  server/routes/data_connections/data_connections_router.ts
  server/routes/datasources/datasources_router.ts
  server/routes/index.ts
Labels: enhancement, backport 2.x, backport 2.14

#1781 Fix metrics single data-point visability
  common/constants/shared.ts
  public/components/visualizations/plotly/plot.tsx
Labels: enhancement, backport 2.x, backport 2.14

#1782 Backport prometheus fix to 2.x
  public/components/custom_panels/helpers/utils.tsx
Labels: backport 2.14

#1792 Fix all the unit tests
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap
  public/components/visualizations/plotly/__tests__/__snapshots__/plotly.test.tsx.snap
Labels: maintenance

#1791 MDS Support for trace analytics (#1752) [Manual backport]
  opensearch_dashboards.json
  public/components/app.tsx
  public/components/application_analytics/components/config_components/service_config.tsx
  public/components/application_analytics/components/flyout_components/service_detail_flyout.tsx
  public/components/index.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/dashboard.test.tsx
  public/components/trace_analytics/components/dashboard/dashboard.tsx
  public/components/trace_analytics/components/dashboard/dashboard_content.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/service_view.test.tsx
  public/components/trace_analytics/components/services/__tests__/services.test.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/trace_view.test.tsx
  public/components/trace_analytics/components/traces/__tests__/traces.test.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/requests/dashboard_request_handler.ts
  public/components/trace_analytics/requests/request_handler.ts
  public/components/trace_analytics/requests/services_request_handler.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
  public/framework/core_refs.ts
  public/plugin.tsx
  public/types.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/trace_analytics_dsl_router.ts
Labels: backport-failed

#1794 Adding test for clear cache on logout
  common/constants/data_sources.ts
  public/framework/catalog_cache/cache_intercept.test.ts
  public/framework/catalog_cache/cache_intercept.ts
Labels: backport 2.x, maintenance, backport 2.14

#1805 remove defaulting to query assist time range
  public/components/event_analytics/explorer/log_explorer.tsx
Labels: bug, backport 2.x, backport main

#1808 Update snapshots on 2.14
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap
  public/components/visualizations/plotly/__tests__/__snapshots__/plotly.test.tsx.snap
Labels: bug

#1810 Fix data connection api 404 error
  server/routes/data_connections/data_connections_router.ts
Labels: bug, backport 2.x, backport main, v2.14.0

#1732 Add JSON5 parsing capabilities for integration configs
  package.json
  server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
  server/adaptors/integrations/repository/fs_data_adaptor.ts
  yarn.lock
Labels: enhancement, backport 2.x, integrations

#1818 Fix otel queries metrics to match OTEL spec
  server/adaptors/metrics/metrics_analytics_adaptor.ts
Labels: enhancement, backport 2.x, metrics, backport 2.14

#1823 Fix window start backtick during MV creation
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/column_expression.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/query_builder.tsx
  test/accelerations.ts
Labels: bug, backport 2.x

#1825 Refactor away integrations adaptor class
  server/adaptors/integrations/integrations_adaptor.ts
  server/adaptors/integrations/integrations_manager.ts
  server/routes/integrations/__tests__/integrations_router.test.ts
  server/routes/integrations/integrations_router.ts
Labels: backport 2.x, integrations, maintenance

#1829 Move Cypress related dependencies to devDependencies and remove one unused dependency
  package.json
  yarn.lock
Labels: enhancement, backport 2.x

#1817 Improve query assist user experiences
  public/components/common/search/__tests__/search.test.tsx
  public/components/common/search/query_area.tsx
  public/components/common/search/search.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/log_explorer.tsx
  public/components/event_analytics/explorer/query_assist/__tests__/__snapshots__/callouts.test.tsx.snap
  public/components/event_analytics/explorer/query_assist/callouts.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/explorer/timechart/__tests__/__snapshots__/timechart.test.tsx.snap
  public/components/event_analytics/explorer/timechart/__tests__/timechart.test.tsx
  public/components/event_analytics/explorer/timechart/__tests__/utils.test.ts
  public/components/event_analytics/explorer/timechart/hits_counter/__tests__/__snapshots__/hits_counter.test.tsx.snap
  public/components/event_analytics/explorer/timechart/hits_counter/__tests__/hits_counter.test.tsx
  public/components/event_analytics/explorer/timechart/hits_counter/hits_counter.tsx
  public/components/event_analytics/explorer/timechart/hits_counter/index.ts
  public/components/event_analytics/explorer/timechart/index.ts
  public/components/event_analytics/explorer/timechart/timechart.tsx
  public/components/event_analytics/explorer/timechart/timechart_header/__tests__/__snapshots__/timechart_header.test.tsx.snap
  public/components/event_analytics/explorer/timechart/timechart_header/__tests__/timechart_header.test.tsx
  public/components/event_analytics/explorer/timechart/timechart_header/index.ts
  public/components/event_analytics/explorer/timechart/timechart_header/timechart_header.tsx
  public/components/event_analytics/explorer/timechart/utils.ts
  public/components/event_analytics/home/home.tsx
Labels: enhancement, backport 2.x

#1842 [2.x] Improve query assist user experiences (#1817)
  public/components/common/search/__tests__/search.test.tsx
  public/components/common/search/query_area.tsx
  public/components/common/search/search.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/log_explorer.tsx
  public/components/event_analytics/explorer/query_assist/__tests__/__snapshots__/callouts.test.tsx.snap
  public/components/event_analytics/explorer/query_assist/callouts.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/explorer/timechart/__tests__/__snapshots__/timechart.test.tsx.snap
  public/components/event_analytics/explorer/timechart/__tests__/timechart.test.tsx
  public/components/event_analytics/explorer/timechart/__tests__/utils.test.ts
  public/components/event_analytics/explorer/timechart/hits_counter/__tests__/__snapshots__/hits_counter.test.tsx.snap
  public/components/event_analytics/explorer/timechart/hits_counter/__tests__/hits_counter.test.tsx
  public/components/event_analytics/explorer/timechart/hits_counter/hits_counter.tsx
  public/components/event_analytics/explorer/timechart/hits_counter/index.ts
  public/components/event_analytics/explorer/timechart/index.ts
  public/components/event_analytics/explorer/timechart/timechart.tsx
  public/components/event_analytics/explorer/timechart/timechart_header/__tests__/__snapshots__/timechart_header.test.tsx.snap
  public/components/event_analytics/explorer/timechart/timechart_header/__tests__/timechart_header.test.tsx
  public/components/event_analytics/explorer/timechart/timechart_header/index.ts
  public/components/event_analytics/explorer/timechart/timechart_header/timechart_header.tsx
  public/components/event_analytics/explorer/timechart/utils.ts
  public/components/event_analytics/home/home.tsx
Labels: enhancement

#1830 Bug fix for data-sources page
  common/types/data_connections.ts
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_databases.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/manage_data_connections_table.tsx
  public/components/hooks/use_polling.ts
  public/framework/catalog_cache/cache_loader.tsx
  public/plugin.tsx
  public/services/requests/sql.ts
  public/types.ts
Labels: enhancement, backport 2.x

#1831 Updating security reachout email
  SECURITY.md
Labels: documentation, backport 2.x

#1853 Raw Vpc schema integration (1.0.0 parquet )
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/aws_vpc_flow_flint-pre_agg-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/aws_vpc_live_stream_mv_schema-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_skipping_index-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_parquet_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_30min_connections_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_30min_connections_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_60min_connections_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_60min_connections_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_live_all_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_live_week_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_live_week_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_cardinality_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_cardinality_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_total-bytes_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_total-bytes_refresh-1.0.0.sql
Labels: bug, backport 2.x, integrations, backport 2.3

#1857 Traces-analytics bug fix
  public/components/trace_analytics/components/dashboard/dashboard_content.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
Labels: bug, backport 2.x
