Repository opensearch-project/dashboards-observability, pull requests merged in 2024-02, with the labels that each got.

#1386 Hide query assist UI if PPL agent is not created
  common/constants/query_assist.ts
  public/components/event_analytics/explorer/explorer.tsx
  server/routes/query_assist/routes.ts
Labels: bug, backport 2.x

#1401 Optimize searches for integration data
  server/adaptors/integrations/repository/index_data_adaptor.ts
Labels: enhancement, backport 2.x, integrations

#1407 [BUG] Fix Panels PPL Filter
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
Labels: bug

#1413 (query assist) hide dot indices
  public/components/event_analytics/explorer/query_assist/__tests__/hooks.test.ts
  public/components/event_analytics/explorer/query_assist/hooks.ts
Labels: backport main

#1412 Add redirect with error message if integrations template not found
  public/components/integrations/components/integration.tsx
Labels: bug, backport 2.x, integrations

#1420 Add modal for DQL language
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/common/search/search.tsx
  public/components/common/search/sql_search.tsx
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
Labels: enhancement, backport 2.x, backport 2.12

#1424 Change class name to decouple styling from discover
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.scss
Labels: bug, backport 2.x, backport 2.12

#1430 Add release notes for 2.12.0
  release-notes/dashboards-observability.release-notes-2.12.0.0.md
Labels: backport 2.x, maintenance, backport 2.12

#1429 fix explorer stats function typing crash
  common/query_manager/query_parser/ppl_query_parser.ts
Labels: bug, backport 2.x, backport 2.12

#1436 Update dashboards-observability.release-notes-2.12.0.0.md
  release-notes/dashboards-observability.release-notes-2.12.0.0.md
Labels: bug, backport 2.x, backport main

#1451 [BUG] Fixing style overriding issue in dashboards core vizBuilder
  public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.scss
  public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
Labels: bug, backport 2.x, backport main

#1428 Fix jaeger spans key names for filtering
  common/types/trace_analytics.ts
  public/components/trace_analytics/components/traces/flyout_list_item.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: bug, backport 2.x, backport 2.11, backport 2.12

#1454 [CI/CD] Add single version flag during bootstrap to fix version conflicts and update the snapshots
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/lint.yml
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
Labels: backport 2.x, maintenance

#1460 [Backport 2.x] Add single version flag during bootstrap to fix version conflicts
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/lint.yml
Labels: infrastructure, maintenance

#1470 [Feature] Data sources associated objects tab
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/manage/accelerations_recommendation_callout.tsx
  public/components/datasources/components/manage/associated_objects_tab.tsx
  public/components/datasources/components/manage/data_connection.tsx
Labels: enhancement, backport 2.x
