Repository opensearch-project/dashboards-observability, pull requests merged in 2024-03, with the labels that each got.

#1476 Flint bug fix explorer failure
  common/types/explorer.ts
  public/components/common/search/direct_search.tsx
  public/plugin.ts
  server/routes/datasources/datasources_router.ts
Labels: backport 2.x, maintenance

#1475 [Feature] Accelerations Tab and Flyout Skeletons
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_details_tab.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_sql_tab.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/accelerations_schema_tab.tsx
  public/components/datasources/components/manage/accelerations/helpers/utils.tsx
  public/components/datasources/components/manage/associated_objects/accelerations_recommendation_callout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/plugin.tsx
Labels: enhancement

#1480 (query assist) show error toasts if summary is disabled
  public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
Labels: backport 2.x

#1447 remove hardcoded width for generate ppl button
  public/components/event_analytics/explorer/query_assist/input.tsx
Labels: backport 2.x, backport 2.12

#1486 [Backport 2.x] Data sources associated objects tab (#1470)
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/manage/accelerations_recommendation_callout.tsx
  public/components/datasources/components/manage/associated_objects_tab.tsx
  public/components/datasources/components/manage/data_connection.tsx
Labels: enhancement, backport-failed

#1489 [Backport 2.x] Accelerations Tab and Flyout Skeletons
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_details_tab.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_sql_tab.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/accelerations_schema_tab.tsx
  public/components/datasources/components/manage/accelerations/helpers/utils.tsx
  public/components/datasources/components/manage/associated_objects/accelerations_recommendation_callout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/plugin.tsx
Labels: enhancement, backport-failed

#1490 [Feature] Remove index store region and index store URI for data connection panel
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/manage/data_connection.tsx
Labels: enhancement, backport 2.x

#1474 [Feature] Associated objects searchbar filters
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/associated_objects_tab.test.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/components/datasources/components/manage/data_connection.tsx
Labels: enhancement, backport-failed

#1482 (query assist) get agent id through config API
  server/index.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/query_assist/routes.ts
  server/routes/query_assist/utils/__tests__/agents.test.ts
  server/routes/query_assist/utils/agents.ts
  server/routes/query_assist/utils/constants.ts
Labels: backport 2.x, v2.13.0

#1494 Update names and descriptions for integrations
  server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_cloudfront/aws_cloudfront-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_cloudfront/static/logo.png
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_rds/aws_rds-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_s3/aws_s3-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_waf/static/logo.jpg
  server/adaptors/integrations/__data__/repository/aws_waf/static/logo.png
  server/adaptors/integrations/__data__/repository/haproxy/haproxy-1.0.0.json
  server/adaptors/integrations/__data__/repository/k8s/k8s-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: documentation, backport 2.x, integrations, maintenance

#1498 Update integration format for better handling of multiple asset types
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/testing_constants.ts
  public/components/integrations/components/available_integration_overview_page.tsx
  public/components/integrations/components/create_integration_helpers.ts
  public/components/integrations/components/integration_assets_panel.tsx
  public/components/integrations/components/setup_integration.tsx
  server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_cloudfront/aws_cloudfront-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_rds/aws_rds-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_s3/aws_s3-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.0.0.json
  server/adaptors/integrations/__data__/repository/haproxy/haproxy-1.0.0.json
  server/adaptors/integrations/__data__/repository/k8s/k8s-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/__test__/json_repository.test.ts
  server/adaptors/integrations/__test__/local_fs_repository.test.ts
  server/adaptors/integrations/__test__/migrations.test.ts
  server/adaptors/integrations/__test__/validators.test.ts
  server/adaptors/integrations/integrations_adaptor.ts
  server/adaptors/integrations/integrations_builder.ts
  server/adaptors/integrations/integrations_manager.ts
  server/adaptors/integrations/migrations.ts
  server/adaptors/integrations/repository/__test__/integration_reader.test.ts
  server/adaptors/integrations/repository/integration_reader.ts
  server/adaptors/integrations/repository/utils.ts
  server/adaptors/integrations/types.ts
  server/adaptors/integrations/validators.ts
  server/plugin.ts
  test/constants.ts
Labels: enhancement, backport 2.x, integrations

#1500 Catalog cache and Session update for async queries
  common/constants/data_sources.ts
  common/constants/shared.ts
  common/types/data_connections.ts
  common/utils/query_session_utils.ts
  common/utils/shared.ts
  public/components/common/search/direct_search.tsx
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/framework/catalog_cache/cache_intercept.ts
  public/framework/catalog_cache/cache_loader.test.tsx
  public/framework/catalog_cache/cache_loader.tsx
  public/framework/catalog_cache/cache_manager.test.tsx
  public/framework/catalog_cache/cache_manager.ts
  public/plugin.tsx
  public/services/saved_objects/saved_object_loaders/explorer_saved_object_loader.ts
  test/datasources.ts
Labels: enhancement, backport 2.x

#1496 [Feature] Add flyout pages to associated objects table
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx
  public/components/datasources/components/__tests__/associated_objects_tab.test.tsx
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/plugin.tsx
Labels: enhancement, backport 2.x

#1506 [Maintenance] Bump plugin version to 2.13.0
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: enhancement, maintenance

#1463 Fixing Flaky Panels Test
  .cypress/integration/panels_test/panels.spec.ts
Labels: backport 2.x, maintenance

#1508 Move create acceleration flyout from workbench to datasources
  common/constants/data_sources.ts
  common/types/data_connections.ts
  public/components/datasources/components/manage/accelerations/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create/__tests__/__snapshots__/create_acceleration_header.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create/__tests__/create_acceleration.test.tsx
  public/components/datasources/components/manage/accelerations/create/__tests__/create_acceleration_header.test.tsx
  public/components/datasources/components/manage/accelerations/create/__tests__/utils.test.tsx
  public/components/datasources/components/manage/accelerations/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create/create_acceleration_header.tsx
  public/components/datasources/components/manage/accelerations/create/utils.tsx
  public/components/datasources/components/manage/accelerations/selectors/__tests__/__snapshots__/define_index_options.test.tsx.snap
  public/components/datasources/components/manage/accelerations/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap
  public/components/datasources/components/manage/accelerations/selectors/__tests__/__snapshots__/index_type_selector.test.tsx.snap
  public/components/datasources/components/manage/accelerations/selectors/__tests__/__snapshots__/source_selector.test.tsx.snap
  public/components/datasources/components/manage/accelerations/selectors/__tests__/define_index_options.test.tsx
  public/components/datasources/components/manage/accelerations/selectors/__tests__/index_setting_options.test.tsx
  public/components/datasources/components/manage/accelerations/selectors/__tests__/index_type_selector.test.tsx
  public/components/datasources/components/manage/accelerations/selectors/__tests__/source_selector.test.tsx
  public/components/datasources/components/manage/accelerations/selectors/define_index_options.tsx
  public/components/datasources/components/manage/accelerations/selectors/index_setting_options.tsx
  public/components/datasources/components/manage/accelerations/selectors/index_type_selector.tsx
  public/components/datasources/components/manage/accelerations/selectors/source_selector.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/__tests__/__snapshots__/query_visual_editor.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/__tests__/query_builder.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/__tests__/query_visual_editor.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/covering_index/__tests__/__snapshots__/covering_index_builder.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/covering_index/__tests__/covering_index_builder.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/covering_index/covering_index_builder.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/__snapshots__/add_column_popover.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/__snapshots__/column_expression.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/__snapshots__/group_by_tumble_expression.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/__snapshots__/materialized_view_builder.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/add_column_popover.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/column_expression.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/group_by_tumble_expression.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/__tests__/materialized_view_builder.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/add_column_popover.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/column_expression.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/group_by_tumble_expression.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/materialized_view/materialized_view_builder.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/query_builder.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/query_visual_editor.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/__tests__/__snapshots__/add_fields_modal.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/__tests__/__snapshots__/delete_fields_modal.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/__tests__/__snapshots__/skipping_index_builder.test.tsx.snap
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/__tests__/add_fields_modal.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/__tests__/delete_fields_modal.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/__tests__/skipping_index_builder.test.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/add_fields_modal.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/delete_fields_modal.tsx
  public/components/datasources/components/manage/accelerations/visual_editors/skipping_index/skipping_index_builder.tsx
  test/accelerations.ts
Labels: maintenance

#1501 Update integrations to allow custom checkpoint locations
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/setup_integration.test.tsx
  public/components/integrations/components/setup_integration.tsx
  server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_mv_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql
Labels: bug, backport 2.x, integrations

#1505 Minor integration name updates
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/integration.tsx
Labels: backport 2.x, integrations, maintenance

#1507 [Backport 2.x] Add flyout pages to associated objects table
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx
  public/components/datasources/components/__tests__/associated_objects_tab.test.tsx
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/plugin.tsx
Labels: enhancement

#1513 Expose create acceleration flyout, update acceleration docs link
  common/constants/data_connections.ts
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/manage/accelerations/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create/__tests__/__snapshots__/create_acceleration_header.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create/__tests__/create_acceleration.test.tsx
  public/components/datasources/components/manage/accelerations/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/selectors/__tests__/__snapshots__/source_selector.test.tsx.snap
  public/components/datasources/components/manage/accelerations/selectors/__tests__/source_selector.test.tsx
  public/components/datasources/components/manage/accelerations/selectors/index_type_selector.tsx
  public/components/datasources/components/manage/accelerations/selectors/source_selector.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/plugin.tsx
Labels: enhancement, backport 2.x

#1515 Export observability start interface
  public/index.ts
  public/plugin.tsx
  public/types.ts
Labels: enhancement, backport 2.x

#1479 Changed Explorer Data Grid useage of timestamp
  common/constants/explorer.ts
  common/constants/shared.ts
  public/components/common/search/direct_search.tsx
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
  public/components/event_analytics/explorer/__tests__/data_grid.test.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
Labels: backport 2.x, maintenance

#1525 Add datasource field in accelerations cache
  common/types/data_connections.ts
  public/framework/catalog_cache/cache_loader.test.tsx
  public/framework/catalog_cache/cache_loader.tsx
  public/framework/catalog_cache/cache_manager.test.tsx
  public/framework/catalog_cache/cache_manager.ts
Labels: enhancement, backport 2.x

#1518 Add conditional installation for S3 integrations
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/setup_integration.test.tsx
  public/components/integrations/components/create_integration_helpers.ts
  public/components/integrations/components/setup_integration.tsx
  server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/integrations_adaptor.ts
  server/adaptors/integrations/integrations_builder.ts
  server/adaptors/integrations/integrations_manager.ts
  server/adaptors/integrations/repository/integration_reader.ts
  server/adaptors/integrations/types.ts
  server/adaptors/integrations/validators.ts
  server/routes/integrations/integrations_router.ts
  test/constants.ts
Labels: enhancement, backport 2.x, integrations

#1533 Update data grid snapshots
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
Labels: maintenance

#1521 [Feature] Acceleration components' data implementation
  common/constants/shared.ts
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/datasources/components/__tests__/acceleration_details_flyout.test.tsx
  public/components/datasources/components/__tests__/acceleration_table.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_details_tab.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/accelerations_schema_tab.tsx
  public/components/datasources/components/manage/accelerations/helpers/utils.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/framework/core_refs.ts
  public/plugin.tsx
  public/services/requests/dsl.ts
  server/routes/dsl.ts
Labels: enhancement, backport 2.x

#1523 Update UI styles for query assist
  common/constants/query_assist.ts
  public/components/common/search/query_area.scss
  public/components/common/search/query_area.tsx
  public/components/common/search/search.tsx
  public/components/event_analytics/explorer/log_patterns/log_patterns.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/redux/slices/query_assistant_summarization_slice.ts
  server/routes/query_assist/routes.ts
Labels: backport 2.x, v2.13.0

#1517 [Feature] Add Retrieval from Catalog Cache
  common/types/data_connections.ts
  common/types/explorer.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/connection_details.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/acceleration_details_flyout.test.tsx
  public/components/datasources/components/__tests__/acceleration_table.test.tsx
  public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx
  public/components/datasources/components/__tests__/associated_objects_tab.test.tsx
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_sql_tab.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_refresh_button.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_empty.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_failure.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_loading.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/framework/catalog_cache/cache_loader.tsx
  public/framework/catalog_cache/cache_manager.test.tsx
  public/framework/catalog_cache/cache_manager.ts
  public/plugin.tsx
  test/datasources.ts
Labels: enhancement, backport 2.x

#1544 Add actual integration queries to table
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/installed_integrations_table.test.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/setup_integration.tsx
  public/framework/catalog_cache/cache_loader.tsx
  server/adaptors/integrations/types.ts
  test/constants.ts
Labels: enhancement, integrations

#1543 [Log explorer] Remove modal for discover redirection
  public/components/common/search/search.tsx
Labels: enhancement, backport 2.x, v2.13.0

#1549 Adding datasource status and filter for hive tables
  common/constants/data_sources.ts
  common/constants/shared.ts
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/inactive_data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/datasources/components/__tests__/inactive_data_connection.test.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/inactive_data_connection.tsx
  public/components/datasources/components/manage/manage_data_connections_table.tsx
  public/framework/catalog_cache/cache_loader.test.tsx
  public/framework/catalog_cache/cache_loader.tsx
  server/routes/data_connections/data_connections_router.ts
  test/datasources.ts
Labels: enhancement, backport 2.x

#1548 Implement redirection to explorer within data sources
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/plugin.tsx
Labels: enhancement, backport 2.x

#1555 Copy Updates: Integration Flows -> Integration Resources
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/setup_integration.tsx
Labels: backport 2.x, ux-integration, maintenance

#1551 Data Sources component Improvements and bug fixes
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/acceleration_table.test.tsx
  public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx
  public/components/datasources/components/__tests__/associated_objects_tab.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/plugin.tsx
  public/types.ts
  test/datasources.ts
Labels: enhancement

#1560 Allow browsing integrations in Flyout from Data Sources page
  common/utils/shared.ts
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/installed_integrations_table.test.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/testing_constants.ts
  public/components/integrations/components/available_integration_card_view.tsx
  public/components/integrations/components/available_integration_overview_page.tsx
  public/components/integrations/components/available_integration_table.tsx
  public/components/integrations/components/integration_header.tsx
  test/constants.ts
Labels: enhancement, integrations, ux-integration

#1540 [Feature] Acceleration Actions Implementation
  public/components/datasources/components/__tests__/acceleration_action_overlay.test.tsx
  public/components/datasources/components/__tests__/acceleration_operation.test.tsx
  public/components/datasources/components/__tests__/acceleration_table.test.tsx
  public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_action_overlay.tsx
  public/components/datasources/components/manage/accelerations/acceleration_details_flyout.tsx
  public/components/datasources/components/manage/accelerations/acceleration_operation.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_details_tab.tsx
  public/components/datasources/components/manage/accelerations/flyout_modules/acceleration_sql_tab.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/plugin.tsx
  public/types.ts
  test/datasources.ts
Labels: enhancement, backport 2.x

#1561 Add integration installation to data sources flyout
  .cypress/integration/integrations_test/integrations.spec.js
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/installed_integrations_table.test.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/datasources/components/new/new_datasource_card_view.tsx
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/setup_integration.test.tsx
  public/components/integrations/components/available_integration_card_view.tsx
  public/components/integrations/components/available_integration_overview_page.tsx
  public/components/integrations/components/available_integration_table.tsx
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/setup_integration.tsx
Labels: enhancement, integrations, ux-integration

#1552 Add auto-suggestions for skipping index definition and export types
  common/constants/shared.ts
  common/types/data_connections.ts
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/create_acceleration.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/utils.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/preview_sql_defintion.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/source_selector.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/preview_sql_defintion.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/source_selector.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/preview_sql_defintion.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_databases.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/__tests__/__snapshots__/query_visual_editor.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/__snapshots__/generate_fields.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/__snapshots__/skipping_index_builder.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/generate_fields.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/generate_fields.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/skipping_index_builder.tsx
  public/framework/core_refs.ts
  public/framework/datasources/direct_query_hook.tsx
  public/plugin.tsx
  public/types.ts
Labels: enhancement, backport 2.x

#1567 Integrations: Update delete modal to support custom verify prompt
  .cypress/integration/integrations_test/integrations.spec.js
  public/components/common/helpers/delete_modal.tsx
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/added_integration_table.tsx
Labels: enhancement, backport 2.x

#1559 Fixed small bugs in explorer
  public/components/common/search/direct_search.tsx
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
Labels: enhancement, backport 2.x

#1554 Implement results from no timestamp in Explorer
  public/components/common/query_utils/index.ts
  public/components/common/search/date_picker.tsx
  public/components/common/search/search.tsx
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
  public/components/event_analytics/explorer/__tests__/data_grid.test.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx
  public/services/data_fetchers/ppl/ppl_data_fetcher.ts
  public/services/saved_objects/saved_object_loaders/explorer_saved_object_loader.ts
Labels: enhancement, backport 2.x

#1572 Release notes 2.13
  release-notes/dashboards-observability.release-notes-2.13.0.0.md
Labels: maintenance

#1575 add info callout for s3 datasources
  public/components/event_analytics/explorer/log_explorer.scss
  public/components/event_analytics/explorer/no_results.tsx
Labels: enhancement, backport 2.x

#1576 Update loading state for tables fields in create acceleration flyout
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_type_selector.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_type_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_databases.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/query_visual_editor.tsx
Labels: enhancement, backport 2.x

#1574 [Bug Fix] Flint datasource 2.13 bug bash fix
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/acceleration_table.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_action_overlay.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/data_connection.tsx
Labels: bug, enhancement, backport 2.x, backport 2.13

#1588 Disable close button when integration is being installed
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/integrations/components/setup_integration.tsx
Labels: bug, backport 2.x, ux-integration, backport 2.13

#1590 Fix datagrid snapshots for 2.x
  public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
Labels: maintenance, backport 2.13

#1589 Enable integration install flyout for other install buttons
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/installed_integrations_table.test.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/datasources/components/manage/manage_data_connections_table.tsx
  public/components/integrations/components/create_integration_helpers.ts
  public/components/integrations/components/setup_integration.tsx
Labels: bug, backport 2.x, ux-integration, backport 2.13

#1598 Updating usePolling to cleanup after unmount
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_empty.tsx
  public/components/hooks/use_polling.ts
Labels: bug, backport 2.x, backport 2.13

#1599 Fix create acceleration bugs
  common/constants/data_sources.ts
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/utils.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/define_index_options.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_advanced_settings.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_type_selector.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/define_index_options.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_setting_options.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_type_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/preview_sql_defintion.tsx
Labels: enhancement, backport 2.x, backport 2.13

#1605 Sanitize create acceleration queries and direct queries
  common/constants/data_sources.ts
  public/components/common/search/direct_search.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration_button.tsx
Labels: bug, backport 2.x, backport 2.13

#1613 Add basic developer docs for integration setup and config
  docs/integrations/README.md
  docs/integrations/config.md
  docs/integrations/setup.md
Labels: documentation, backport 2.x, integrations

#1612 Fix DSL router, update UI for query assist
  public/components/event_analytics/explorer/query_assist/input.tsx
  server/routes/dsl.ts
Labels: bug, backport 2.x, backport 2.13

#1617 Create acceleration flyout bug fixes
  common/constants/data_sources.ts
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration_button.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_setting_options.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/preview_sql_defintion.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/__tests__/__snapshots__/query_visual_editor.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/group_by_tumble_expression.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/__snapshots__/skipping_index_builder.test.tsx.snap
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/skipping_index_builder.tsx
  public/framework/catalog_cache/cache_loader.tsx
  public/framework/datasources/direct_query_hook.tsx
Labels: bug, backport 2.x, backport 2.13

#1609 Fixed bugs in explorer redirection
  common/constants/autocomplete.ts
  common/types/data_connections.ts
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/common/search/autocomplete.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/manage_data_connections_table.tsx
  public/components/event_analytics/__tests__/__snapshots__/no_results.test.tsx.snap
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/sidebar/observability_sidebar.tsx
  public/components/event_analytics/explorer/visualizations/direct_query_vis.tsx
Labels: bug, backport 2.x, backport 2.13

#1618 Bug fixes and UI updates for datasources
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/manage/accelerations/acceleration_action_overlay.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration_button.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/plugin.tsx
  public/types.ts
  test/datasources.ts
Labels: bug, backport 2.x, backport 2.13

#1627 Updating snapshot to fix build
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
Labels: bug, backport 2.x, backport 2.13

#1631 Updating catch for guardrails
  common/constants/query_assist.ts
  public/components/event_analytics/explorer/query_assist/input.tsx
  server/routes/query_assist/routes.ts
Labels: bug, backport 2.x, backport 2.13

#1634 Clear cache on any 401 response errors
  public/framework/catalog_cache/cache_intercept.ts
Labels: bug, backport 2.x, backport main

#1639 Enable query assist by default
  server/index.ts
Labels: backport 2.x, backport 2.13

#1643 [BUGFIX] Fix integration data reading double escape
  server/adaptors/integrations/repository/integration_reader.ts
Labels: bug, backport 2.x, integrations, backport 2.13

#1647 Fix integration flyout successes
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/integrations/components/setup_integration.tsx
Labels: bug, backport 2.x, integrations, ux-integration, backport 2.13

#1646 Clear callout in query assist
  public/components/event_analytics/explorer/query_assist/input.tsx
Labels: enhancement, backport 2.x, backport 2.13

#1650 Update intercept to check logout request
  public/framework/catalog_cache/cache_intercept.ts
  public/plugin.tsx
Labels: bug, backport 2.x, backport main

#1658 Bug Fix for Undefined Association
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
Labels: bug, backport 2.x, backport 2.13

#1662 Correctly Utilize Cache in Tables Flyout
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
Labels: bug, backport 2.x, backport 2.13
