Repository opensearch-project/dashboards-observability, pull requests merged in 2024-12, with the labels that each got.

#2269 [Cypress Updates] Metrics updates
  .cypress/integration/metrics_analytics_test/metrics_analytics.spec.js
  .cypress/utils/event_analytics/helpers.js
Labels: backport 2.x, maintenance

#2228 Remove fallback restore keys from build cache
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
Labels: infrastructure

#2261 [Cypress Updates] App analytics updates
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/home.tsx
  public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
Labels: backport 2.x, maintenance

#2257 Traces - Gantt chart / Span list rework
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/application_analytics/components/flyout_components/trace_detail_render.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/span_detail_panel.test.tsx
  public/components/trace_analytics/components/traces/__tests__/span_detail_table.test.tsx
  public/components/trace_analytics/components/traces/service_breakdown_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/index.scss
  public/components/visualizations/plotly/plot.tsx
Labels: enhancement, backport 2.x, mds-2.18.0

#2268 Fix fetching workspace visualizations error
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/paragraphs.test.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: bug, backport 2.x

#2276 [Manual Backport 2.x] [Cypress Updates] App analytics updates (#2261)
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/home.tsx
  public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
Labels: maintenance

#2279 [Bug] Fix notebook routes for savedNotebook endpoints
  public/components/notebooks/components/main.tsx
  public/components/notebooks/components/notebook.tsx
  server/routes/notebooks/paraRouter.ts
Labels: bug, backport 2.x, notebooks

#2280 [Cypress Updates] Fix flaky notebooks test
  .cypress/integration/notebooks_test/notebooks.spec.js
Labels: backport 2.x, maintenance, notebooks

#2283 [Manual Backport 2.x ] 2257 to 2.x Traces - Gantt chart / Span list rework
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/application_analytics/components/flyout_components/trace_detail_render.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/span_detail_panel.test.tsx
  public/components/trace_analytics/components/traces/__tests__/span_detail_table.test.tsx
  public/components/trace_analytics/components/traces/service_breakdown_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/index.scss
  public/components/visualizations/plotly/plot.tsx
Labels: enhancement

#2278 [Bug] Updated notebooks reporting button render
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/__tests__/notebook.test.tsx
  public/components/notebooks/components/notebook.tsx
Labels: bug, backport 2.x, notebooks

#2284 [Bug] Fix SQL/PPL crash with incorrect query
  .cypress/integration/notebooks_test/notebooks.spec.js
  .cypress/support/constants.js
  .cypress/utils/constants.js
  server/services/queryService.ts
Labels: bug, backport 2.x, notebooks

#2275 [Cypress Updates] Event explorer updates
  .cypress/integration/event_analytics_test/event_analytics.spec.js
  public/components/event_analytics/explorer/events_views/__tests__/__snapshots__/flyout_button.test.tsx.snap
  public/components/event_analytics/explorer/events_views/docViewRow.tsx
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/field.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.tsx
Labels: backport 2.x, maintenance, logs-event-explorer

#2285 [Cypress Updates] Panels updates
  .cypress/integration/panels_test/panels.spec.ts
Labels: backport 2.x, maintenance, observability-dashboards

#2264 [Services map] Update redirection/Focus field rework
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map.test.tsx.snap
  public/components/trace_analytics/components/common/plots/__tests__/service_map.test.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/service_view.test.tsx
  public/components/trace_analytics/components/services/__tests__/services_table.test.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/services/services_table.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/home.tsx
  test/constants.ts
Labels: enhancement, backport 2.x, mds-2.18.0

#2291 Configure OpenSearch Dashboards before running in CI
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
Labels: backport 2.x, maintenance

#2293 Fix flaky cypress tests
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/integration/event_analytics_test/event_analytics.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/app_constants.js
Labels: bug, backport 2.x

#2294 Gantt Chart / Service Map followup
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
Labels: bug, backport 2.x
