Repository opensearch-project/dashboards-observability, pull requests merged in 2024-06, with the labels that each got.

#1834 Enhanced UX for S3 connections with lake formation in Data sources management and Logs explorer
  common/types/data_connections.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/source_selector.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_type_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/datasources/components/manage/manage_data_connections_table.tsx
  public/components/datasources/icons/security-lake-logo.svg
  public/components/datasources/utils/helpers.ts
  public/components/event_analytics/__tests__/no_results.test.tsx
  public/components/event_analytics/explorer/accelerate_callout.tsx
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/components/event_analytics/explorer/datasources/tables_flyout.tsx
  public/components/event_analytics/explorer/direct_query_running.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/visualizations/direct_query_vis.tsx
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/components/setup_integration_inputs_security_lake.tsx
  public/components/trace_analytics/components/dashboard/dashboard_content.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/framework/core_refs.ts
  public/framework/datasource_pluggables/types.ts
  public/framework/datasources/obs_opensearch_datasource.ts
  public/plugin.tsx
Labels: enhancement, backport 2.x

#1865 Fix traces index schema bug
  server/adaptors/integrations/__data__/repository/otel-services/schemas/traces-1.0.0.mapping.json
Labels: bug, integrations

#1860 [Integration] Integration enhancements
  server/adaptors/integrations/__data__/repository/amazon_cloudfront/amazon_cloudfront-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_cloudfront/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_elb/amazon_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/amazon_s3/amazon_s3-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_s3/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql
  server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
  server/adaptors/integrations/__data__/repository/apache/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.1.0.json
  server/adaptors/integrations/__data__/repository/aws_waf/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.1.0.json
  server/adaptors/integrations/__data__/repository/haproxy/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/haproxy/haproxy-1.1.0.json
  server/adaptors/integrations/__data__/repository/nginx/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: enhancement, backport 2.x, integrations, backport 2.13

#1870 [Backport 2.x] Integration enhancements
  server/adaptors/integrations/__data__/repository/amazon_cloudfront/amazon_cloudfront-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_cloudfront/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_elb/amazon_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/amazon_s3/amazon_s3-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_s3/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql
  server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
  server/adaptors/integrations/__data__/repository/apache/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.1.0.json
  server/adaptors/integrations/__data__/repository/aws_waf/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.1.0.json
  server/adaptors/integrations/__data__/repository/haproxy/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/haproxy/haproxy-1.1.0.json
  server/adaptors/integrations/__data__/repository/nginx/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: enhancement

#1872 Fix dead links
  .github/ISSUE_TEMPLATE/integration_request.md
  .lycheeignore
  README.md
  public/components/notebooks/docs/dev/Build_Documentation.md
  public/components/notebooks/docs/dev/OpenSearch-Dashboards-Notebooks-Design-Proposal.md
  public/components/notebooks/docs/dev/Usage_Documentation.md
  server/adaptors/integrations/__data__/repository/amazon_elb/info/INGESTION.md
  server/adaptors/integrations/__data__/repository/amazon_elb/info/README.md
  server/adaptors/integrations/__data__/repository/amazon_rds/assets/README.md
  server/adaptors/integrations/__data__/repository/amazon_rds/info/README.md
  server/adaptors/integrations/__data__/repository/amazon_s3/info/README.md
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/README.md
  server/adaptors/integrations/__data__/repository/otel-services/info/DemoLandingPage.md
Labels: backport 2.x, maintenance

#1874 Update 2.x to 2.15.0
  opensearch_dashboards.json
  package.json
Labels: release, v2.15.0

#1875 [Backport 2.14] Raw Vpc schema integration (1.0.0 parquet )
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.0.0.json
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/aws_vpc_live_stream_mv_schema-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_skipping_index-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_30min_connections_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_30min_connections_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_60min_connections_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_agg_60min_connections_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_live_all_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_live_week_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_live_week_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_cardinality_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_cardinality_refresh-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_total-bytes_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/vpc_window-agg_60min_dest_ip_total-bytes_refresh-1.0.0.sql
Labels: enhancement

#1879 Add 'check for version' link in the integration details page
  public/components/integrations/components/__tests__/__snapshots__/integration_details.test.tsx.snap
  public/components/integrations/components/integration_details_panel.tsx
Labels: enhancement, backport 2.x, integrations, v2.15.0

#1876 added supoort for metrics MDS
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/metrics/helpers/utils.tsx
  public/components/metrics/index.tsx
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/sidebar.tsx
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/metrics/view/metrics_grid.tsx
  public/services/requests/ppl.ts
  server/adaptors/metrics/metrics_analytics_adaptor.ts
  server/routes/data_connections/data_connections_router.ts
  server/routes/index.ts
  server/routes/metrics/metrics_rounter.ts
  server/routes/ppl.ts
  server/services/facets/ppl_facet.ts
Labels: enhancement, backport 2.x

#1868 Add applicable_data_sources field to workflows definition
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/__tests__/setup_integration_inputs.test.tsx
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json
  server/adaptors/integrations/types.ts
  server/adaptors/integrations/validators.ts
Labels: enhancement, backport 2.x, integrations, v2.15.0

#1888 Add applicable_data_sources field to workflows definition
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/__tests__/setup_integration_inputs.test.tsx
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json
  server/adaptors/integrations/types.ts
  server/adaptors/integrations/validators.ts
Labels: enhancement, integrations, ux-integration

#1844 maintenance: Move mocha to dev dependencies
  package.json
  yarn.lock
Labels: backport 2.x, maintenance

#1894 Minor bug fixes for trace analytics v2
  public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap
  public/components/trace_analytics/components/common/plots/service_map_scale.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/services_table.tsx
  public/components/trace_analytics/home.tsx
Labels: bug, v2.15.0

#1893 [Backport 2.x] Minor bug fixes for trace analytics v2 (#1894)
  public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap
  public/components/trace_analytics/components/common/plots/service_map_scale.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/services_table.tsx
  public/components/trace_analytics/home.tsx
Labels: bug, v2.15.0

#1892 [Backport 2.x] manual backport of otel-metrics pr
  .cypress/integration/metrics_analytics_test/metrics_analytics.spec.js
  .cypress/integration/panels_test/panels.spec.ts
  .cypress/utils/metrics_constants.js
  common/constants/metrics.ts
  common/constants/shared.ts
  common/types/explorer.ts
  common/types/metrics.ts
  public/components/application_analytics/helpers/utils.tsx
  public/components/common/query_utils/__tests__/query_utils.test.tsx
  public/components/common/query_utils/index.ts
  public/components/custom_panels/custom_panel_view.tsx
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/panel_grid/panel_grid.tsx
  public/components/custom_panels/panel_modules/panel_grid/panel_grid_so.tsx
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/event_analytics/home/saved_objects_table.tsx
  public/components/event_analytics/utils/utils.tsx
  public/components/metrics/helpers/utils.tsx
  public/components/metrics/index.tsx
  public/components/metrics/redux/slices/__tests__/metric_slice.test.tsx
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/__tests__/sidebar.test.tsx
  public/components/metrics/sidebar/data_source_picker.tsx
  public/components/metrics/sidebar/index_picker.tsx
  public/components/metrics/sidebar/metric_name.tsx
  public/components/metrics/sidebar/metrics_accordion.tsx
  public/components/metrics/sidebar/sidebar.tsx
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/metrics/view/metrics_grid.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap
  public/components/visualizations/charts/lines/line.tsx
  public/components/visualizations/saved_object_visualization.tsx
  public/components/visualizations/visualization.tsx
  public/components/visualizations/visualization_chart.tsx
  public/embeddable/observability_embeddable.tsx
  public/services/saved_objects/event_analytics/saved_objects.ts
  public/services/saved_objects/saved_object_client/osd_saved_objects/osd_saved_object_client.ts
  public/services/saved_objects/saved_object_client/osd_saved_objects/saved_searches.ts
  public/services/saved_objects/saved_object_client/osd_saved_objects/saved_visualization.ts
  public/services/saved_objects/saved_object_client/ppl/ppl_client.ts
  public/services/saved_objects/saved_object_client/ppl/saved_visualization.ts
  public/services/saved_objects/saved_object_client/saved_objects_actions.ts
  server/adaptors/custom_panels/custom_panel_adaptor.ts
  server/adaptors/metrics/metrics_analytics_adaptor.ts
  server/routes/event_analytics/event_analytics_router.ts
  server/routes/metrics/metrics_rounter.ts
Labels: bug

#1895 [Backport 2.x] Metrics analytics support for MDS
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/metrics/helpers/utils.tsx
  public/components/metrics/index.tsx
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/sidebar.tsx
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/metrics/view/metrics_grid.tsx
  public/services/requests/ppl.ts
  server/adaptors/metrics/metrics_analytics_adaptor.ts
  server/routes/data_connections/data_connections_router.ts
  server/routes/index.ts
  server/routes/metrics/metrics_rounter.ts
  server/routes/ppl.ts
  server/services/facets/ppl_facet.ts
Labels: enhancement, v2.15.0

#1887 Implement upload flyout for integrations
  common/constants/integrations.ts
  public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/upload_flyout.test.tsx.snap
  public/components/integrations/components/__tests__/upload_flyout.test.tsx
  public/components/integrations/components/integration_details_panel.tsx
  public/components/integrations/components/integration_header.tsx
  public/components/integrations/components/upload_flyout.tsx
Labels: enhancement, backport 2.x, integrations, ux-integration, v2.15.0

#1896 (query assist) revert removing backticks
  server/routes/query_assist/routes.ts
Labels: bug, backport 2.x, backport 2.15

#1889 Rename Flint instances to S3 Glue
  docs/integrations/setup.md
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  server/adaptors/integrations/__data__/repository/amazon_cloudfront/amazon_cloudfront-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_elb/amazon_elb-1.0.0.json
  server/adaptors/integrations/__data__/repository/amazon_s3/amazon_s3-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/info/Flint-Integration.md
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/info/README.md
  server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/aws_cloudtrail-flint-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.1.0.json
  server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.1.0.json
  server/adaptors/integrations/__data__/repository/haproxy/haproxy-1.1.0.json
  server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Labels: backport 2.x, integrations, maintenance, v2.15.0

#1900 2.15 release notes
  release-notes/dashboards-observability.release-notes-2.15.0.0.md
Labels: documentation, backport 2.x

#1903 Update metrics DSL queries and trace logs index
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/data_source_picker.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  server/adaptors/metrics/metrics_analytics_adaptor.ts
Labels: bug

#1902 Fix loading state UI for event analytics
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/hooks/use_fetch_events.ts
  public/services/data_fetchers/ppl/ppl_data_fetcher.ts
Labels: backport 2.x

#1906 added placeholder change for metrics picker
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/data_source_picker.tsx
  release-notes/dashboards-observability.release-notes-2.15.0.0.md
Labels: bug, backport 2.x, backport 2.15

#1917 [Bug fix] Trace analytics scroll bar reset
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
Labels: bug, backport 2.x

#1919 [Backport 2.x] Bug fix -Trace analytics scroll bar reset (#1917)
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
Labels: bug

#1915 [Enhancement] Remove duplicate description for create s3 datasource flow
  public/components/datasources/components/new/configure_s3_datasource.tsx
Labels: enhancement, backport 2.x

#1730 [BUG-Fixed] #1466 - create observability dashboard after invalid name
  public/components/custom_panels/custom_panel_table.tsx
Labels: bug, backport 2.x
