Repository opensearch-project/dashboards-observability, pull requests merged in 2024-09, with the labels that each got.

#2077 [Feature] OverviewPage made with Content Management
  common/constants/overview.ts
  common/constants/shared.ts
  common/types/overview.ts
  opensearch_dashboards.json
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/getting_started/components/getting_started.tsx
  public/components/getting_started/components/getting_started_queryAndAnalyze.tsx
  public/components/getting_started/components/utils.tsx
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/integration_header.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/overview/components/__tests__/__snapshots__/add_dashboard_callout.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/dashboard_controls.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/select_dashboard_flyout.test.tsx.snap
  public/components/overview/components/__tests__/add_dashboard_callout.test.tsx
  public/components/overview/components/__tests__/dashboard_controls.test.tsx
  public/components/overview/components/__tests__/select_dashboard_flyout.test.tsx
  public/components/overview/components/add_dashboard_callout.tsx
  public/components/overview/components/card_configs.tsx
  public/components/overview/components/dashboard_controls.tsx
  public/components/overview/components/obs_dashboard_state_manager.tsx
  public/components/overview/components/select_dashboard_flyout.tsx
  public/components/overview/components/utils.tsx
  public/components/overview/home.tsx
  public/components/overview/index.scss
  public/framework/core_refs.ts
  public/index.scss
  public/plugin.tsx
  public/plugin_helpers/plugin_headerControl.tsx
  public/plugin_helpers/plugin_nav.tsx
  public/plugin_helpers/plugin_overview.tsx
  public/types.ts
  server/plugin.ts
Labels: enhancement, backport 2.x

#2113 [Backport 2.x][Feature] OverviewPage made with Content Management (#2077)
  common/constants/overview.ts
  common/constants/shared.ts
  common/types/overview.ts
  opensearch_dashboards.json
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/getting_started/components/getting_started.tsx
  public/components/getting_started/components/getting_started_queryAndAnalyze.tsx
  public/components/getting_started/components/utils.tsx
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/integration_header.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/overview/components/__tests__/__snapshots__/add_dashboard_callout.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/dashboard_controls.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/select_dashboard_flyout.test.tsx.snap
  public/components/overview/components/__tests__/add_dashboard_callout.test.tsx
  public/components/overview/components/__tests__/dashboard_controls.test.tsx
  public/components/overview/components/__tests__/select_dashboard_flyout.test.tsx
  public/components/overview/components/add_dashboard_callout.tsx
  public/components/overview/components/card_configs.tsx
  public/components/overview/components/dashboard_controls.tsx
  public/components/overview/components/obs_dashboard_state_manager.tsx
  public/components/overview/components/select_dashboard_flyout.tsx
  public/components/overview/components/utils.tsx
  public/components/overview/home.tsx
  public/components/overview/index.scss
  public/framework/core_refs.ts
  public/index.scss
  public/plugin.tsx
  public/plugin_helpers/plugin_headerControl.tsx
  public/plugin_helpers/plugin_nav.tsx
  public/plugin_helpers/plugin_overview.tsx
  public/types.ts
  server/plugin.ts
Labels: enhancement

#2110 [Feature] UI update to notebooks and applications
  common/utils/set_nav_bread_crumbs.ts
  public/components/application_analytics/components/app_table.tsx
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/note_table.test.tsx
  public/components/notebooks/components/note_table.tsx
Labels: enhancement, backport 2.x, backport 2.17

#2111 [query assist] update api handler to accommodate new ml-commons config response
  server/routes/query_assist/utils/__tests__/agents.test.ts
  server/routes/query_assist/utils/agents.ts
Labels: bug, backport 2.x, backport 2.17

#2100 [Bug]fixed traces bug for missing MDS id
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/components/flyout_components/trace_detail_flyout.tsx
  public/components/application_analytics/components/flyout_components/trace_detail_render.tsx
Labels: enhancement, backport 2.x, backport 2.17

#2125 Update trace analytics landing page to traces and header bug fix
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/trace_side_nav.tsx
Labels: bug, backport 2.x, v2.17.0, backport 2.17

#2108 [BUG]fix add sample notebooks
  public/components/notebooks/components/helpers/modal_containers.tsx
  public/components/notebooks/components/main.tsx
  public/components/notebooks/components/note_table.tsx
Labels: bug, backport 2.x, backport 2.17

#2124 [query assist] update ml-commons response schema
  server/routes/index.ts
  server/routes/query_assist/routes.ts
Labels: enhancement, backport 2.x, v2.17.0, backport 2.17

#2133 Update the actions/upload-artifact from v1 to v4
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
Labels: backport 2.x, maintenance, backport 2.17

#2132 [Release] Add release note for 2.17.0
  release-notes/opensearch-observability.release-notes-2.17.0.0.md
Labels: backport 2.x, maintenance, backport 2.17

#2140 [MDS] Add support for register data sources during the absence of local cluster
  public/plugin.tsx
  release-notes/opensearch-observability.release-notes-2.17.0.0.md
Labels: enhancement, backport 2.x, backport 2.17

#2138 [CVE] Bump the lint-staged from 13.1.0 to 15.2.10
  package.json
  release-notes/opensearch-observability.release-notes-2.17.0.0.md
  yarn.lock
Labels: backport 2.x, maintenance, backport 2.17

#2146 Fix getting started cards re-direction to integrations
  public/components/getting_started/components/getting_started_integrationCards.tsx
Labels: bug, backport 2.x, backport 2.17

#2147 Fix integration imports for table and card view
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/available_integration_card_view.tsx
Labels: bug, v2.17.0, backport 2.17

#2144 [Manual Backport 2.x] Add support for register data sources during the absence of local cluster
  public/plugin.tsx
  release-notes/opensearch-observability.release-notes-2.17.0.0.md
Labels: enhancement, backport 2.17

#2153 [Main only] Rename the MDS feature flag variable to be more explicit
  public/plugin.tsx
Labels: enhancement

#2154 fix(log explorer): show PPL errors in toasts correctly
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/hooks/use_fetch_events.ts
Labels: bug, backport 2.x, backport 2.17

#2152 [Bug] UI changes for overview page, fix re-direction for workspaces
  common/constants/shared.ts
  public/components/getting_started/components/getting_started.tsx
  public/components/getting_started/components/getting_started_collectData.tsx
  public/components/getting_started/components/getting_started_queryAndAnalyze.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/overview/components/__tests__/__snapshots__/add_dashboard_callout.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/dashboard_controls.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/select_dashboard_flyout.test.tsx.snap
  public/components/overview/components/add_dashboard_callout.tsx
  public/components/overview/components/card_configs.tsx
  public/components/overview/components/select_dashboard_flyout.tsx
  public/components/overview/home.tsx
  public/plugin_helpers/plugin_overview.tsx
Labels: bug, backport 2.x, backport 2.17

#2162 Trace analytics ui bug fixes in custom sources
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/common/search_bar.tsx
  public/components/trace_analytics/components/traces/services_list.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
Labels: bug, backport 2.x, backport 2.17

#2165 [Bug] Update observability saved objects to Discover saved objects
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  server/adaptors/integrations/__data__/repository/amazon_cloudfront/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_elb/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/apache/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/example_queries-records-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/aws_waf/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/nginx/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/integrations_builder.ts
Labels: bug, backport 2.x, backport 2.17

#2157 Fix cloudtrail field name mismatch
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-1.0.0.sql
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-records-1.0.0.sql
Labels: bug, backport 2.x, integrations

#2168 UI Adjustments Left Nav, Notebooks, Applications
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/components/configuration.tsx
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/overview/components/card_configs.tsx
  public/plugin_helpers/plugin_nav.tsx
Labels: enhancement, backport 2.x

#2178 Update custom traces table with filters
  common/constants/trace_analytics.ts
  common/types/trace_analytics.ts
  public/components/application_analytics/components/application.tsx
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
  public/components/trace_analytics/components/traces/trace_table_helpers.tsx
  public/components/trace_analytics/components/traces/traces.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/index.scss
  public/components/trace_analytics/requests/queries/traces_queries.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: bug, backport 2.x

#2182 [navigation]feat: update category to flatten menus in analytics(all) use case
  public/plugin_helpers/plugin_nav.tsx
Labels: enhancement, backport 2.x

#2179 [Bug Fix] Fix the VPC integration's MV creation query
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql
Labels: bug, backport 2.x, integrations
