Repository opensearch-project/dashboards-observability, pull requests merged in 2024-08, with the labels that each got.

#2023 [BUG] Traces and Spans tab Fix for application analytics
  public/components/application_analytics/components/application.tsx
Labels: bug, backport 2.x, backport 2.16

#2024 Fix direct url load for trace analytics
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/trace_side_nav.tsx
Labels: bug, backport 2.x, backport 2.16

#2027 [Backport 2.16] Fix direct url load for trace analytics
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/trace_side_nav.tsx
Labels: bug

#2031 [Bug] Getting Started broken link fix for csv
  public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json
Labels: bug

#2037 [Bug] Trace Analytics bugfix for breadcrumbs and id pathing
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/home.tsx
Labels: bug, backport 2.x, backport 2.16

#2038 [Backport 2.16] 2037 to 2.16 Trace Analytics bugfix for breadcrumbs and id pathing
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/home.tsx
Labels: bug

#2046 Fix Observability CI workflow checks
  .cypress/integration/datasources_test/datasources_basic_ui.spec.js
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/link-checker.yml
  public/components/getting_started/getting_started_artifacts/otel-services/assets/getting-started-demo-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/otel-services/assets/otel-index-patterns-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/otel-services/info/Tutorial.md
  server/adaptors/integrations/__data__/repository/otel-services/assets/otel-index-patterns-1.0.0.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0.ndjson
Labels: backport 2.x, infrastructure

#2054 [Backport 2.x] Fix Observability CI workflow checks (#2046)
  .cypress/integration/datasources_test/datasources_basic_ui.spec.js
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/link-checker.yml
  public/components/getting_started/getting_started_artifacts/otel-services/assets/getting-started-demo-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/otel-services/assets/otel-index-patterns-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/otel-services/info/Tutorial.md
  server/adaptors/integrations/__data__/repository/otel-services/assets/otel-index-patterns-1.0.0.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0.ndjson
Labels: maintenance

#2050 [Page Header] New page header for metrics
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap
  public/components/metrics/index.tsx
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/data_source_picker.tsx
  public/components/metrics/sidebar/search_bar.tsx
  public/components/metrics/sidebar/sidebar.scss
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export_panel.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/metrics/top_menu/__tests__/metrics_export.test.tsx
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/metrics/top_menu/metrics_export_panel.tsx
  public/components/metrics/top_menu/top_menu.scss
  public/components/metrics/top_menu/top_menu.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/framework/core_refs.ts
  public/plugin.tsx
Labels: enhancement, backport 2.x

#2060 [Backport 2.x] [Page Header] New page header for metrics (#2050)
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap
  public/components/metrics/index.tsx
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/data_source_picker.tsx
  public/components/metrics/sidebar/search_bar.tsx
  public/components/metrics/sidebar/sidebar.scss
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export_panel.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/metrics/top_menu/__tests__/metrics_export.test.tsx
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/metrics/top_menu/metrics_export_panel.tsx
  public/components/metrics/top_menu/top_menu.scss
  public/components/metrics/top_menu/top_menu.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/framework/core_refs.ts
  public/plugin.tsx
Labels: enhancement

#2082 Adding Ryan, Sean and Adam as dashboards-observability maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, maintenance

#2071 [Look&Feel] Integrations Density and Consistency Improvements
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration_flyout.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_details.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/upload_flyout.test.tsx.snap
  public/components/integrations/components/add_integration_flyout.tsx
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/integration_details_panel.tsx
  public/components/integrations/components/integration_header.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/components/upload_flyout.tsx
Labels: enhancement, backport 2.x

#2072 [Look&Feel] Traces Density and Consistency Improvements
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/trace_analytics/components/common/__tests__/__snapshots__/helper_functions.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filters.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/plots/service_map_node_details.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_error_rates_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/service_trends_plots.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_flyout.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
Labels: backport 2.x, maintenance

#2073 [Look&Feel] Notebooks Density and Consistency Improvements
  .cypress/integration/notebooks_test/notebooks.spec.js
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/helpers/__tests__/__snapshots__/modal_containers.test.tsx.snap
  public/components/notebooks/components/helpers/custom_modals/__tests__/__snapshots__/custom_input_modal.test.tsx.snap
  public/components/notebooks/components/helpers/custom_modals/custom_input_modal.tsx
  public/components/notebooks/components/helpers/custom_modals/reporting_loading_modal.tsx
  public/components/notebooks/components/helpers/modal_containers.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/notebooks/components/paragraph_components/para_input.tsx
  public/components/notebooks/components/paragraph_components/para_output.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: backport 2.x, maintenance

#2074 [Look&Feel] Custom Panels Density and Consistency Improvements
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap
  public/components/custom_panels/custom_panel_table.tsx
  public/components/custom_panels/custom_panel_view.tsx
  public/components/custom_panels/custom_panel_view_so.tsx
  public/components/custom_panels/helpers/__tests__/__snapshots__/custom_input_model.test.tsx.snap
  public/components/custom_panels/helpers/add_visualization_popover.tsx
  public/components/custom_panels/helpers/custom_input_modal.tsx
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout_so.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx
  public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx
Labels: backport 2.x, maintenance

#2078 [Feature] Traces/Services UI update
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/common/live_tail/__tests__/__snapshots__/live_tail_button.test.tsx.snap
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/__tests__/__snapshots__/empty_panel.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout_so.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_description.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/no_access.test.tsx.snap
  public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_header.test.tsx.snap
  public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_table.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration_flyout.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_edit_popover.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filters.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/common/search_bar.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_error_rates_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/services.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_flyout.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
Labels: enhancement, backport 2.x

#2094 [Backport 2.x] [Feature] Traces/Services UI update (#2078)
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/common/live_tail/__tests__/__snapshots__/live_tail_button.test.tsx.snap
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/__tests__/__snapshots__/empty_panel.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout_so.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_description.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/no_access.test.tsx.snap
  public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_header.test.tsx.snap
  public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_table.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration_flyout.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_edit_popover.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filters.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/common/search_bar.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_error_rates_table.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/services.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_flyout.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
Labels: enhancement

#2081 [Page Header] New page header for applications and UI updates
  common/constants/shared.ts
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/components/create.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/custom_panel_table.tsx
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/note_table.tsx
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/plugin_headerControl.tsx
Labels: enhancement, backport 2.x

#2051 [FEATURE] MDS support in Integrations for observability plugin
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/added_integration_table.test.tsx
  public/components/integrations/components/__tests__/testing_constants.ts
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/added_integration_overview_page.tsx
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/create_integration_helpers.ts
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/integrations/components/integration_types.ts
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/home.tsx
  public/components/metrics/top_menu/metrics_export_panel.tsx
  public/components/metrics/top_menu/top_menu.tsx
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/integrations_builder.ts
  server/adaptors/integrations/integrations_manager.ts
  server/adaptors/integrations/types.ts
  server/routes/dsl.ts
  server/routes/integrations/integrations_router.ts
Labels: enhancement, backport 2.x

#2095 [Backport 2.x] [Page Header] New page header for applications and UI updates (#2081)
  common/constants/shared.ts
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/components/create.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/custom_panel_table.tsx
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/note_table.tsx
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/plugin_headerControl.tsx
Labels: enhancement

#2090 [Feature ] Observability dashboards UI update
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap
  public/components/custom_panels/custom_panel_table.tsx
Labels: enhancement, backport 2.x

#2091 Revert security lake changes
  common/constants/data_connections.ts
  common/types/data_connections.ts
  common/types/integrations.ts
  public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap
  public/components/datasources/components/__tests__/acceleration_table.test.tsx
  public/components/datasources/components/manage/accelerations/acceleration_table.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/create_acceleration.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/index_type_selector.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/source_selector.test.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_type_selector.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx
  public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx
  public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
  public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx
  public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
  public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx
  public/components/datasources/components/manage/connection_details.tsx
  public/components/datasources/components/manage/data_connection.tsx
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/datasources/components/manage/manage_data_connections_table.tsx
  public/components/datasources/icons/security-lake-logo.svg
  public/components/datasources/utils/helpers.ts
  public/components/event_analytics/__tests__/no_results.test.tsx
  public/components/event_analytics/explorer/accelerate_callout.tsx
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/components/event_analytics/explorer/datasources/tables_flyout.tsx
  public/components/event_analytics/explorer/direct_query_running.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/visualizations/direct_query_vis.tsx
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/components/setup_integration_inputs_security_lake.tsx
  public/framework/catalog_cache/cache_loader.tsx
  public/framework/core_refs.ts
  public/framework/datasource_pluggables/types.ts
  public/framework/datasources/obs_opensearch_datasource.ts
  public/plugin.tsx
Labels: maintenance

#2092 [Feature] Logs UI update
  public/components/common/search/search.tsx
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/event_analytics/home/__tests__/saved_query_table.test.tsx
  public/components/event_analytics/home/home.scss
  public/components/event_analytics/home/home.tsx
  public/components/event_analytics/home/saved_objects_table.tsx
Labels: enhancement, backport 2.x

#2096 [Backport 2.X] MDS support in Integrations for observability plugin (#2051)
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/added_integration_table.test.tsx
  public/components/integrations/components/__tests__/testing_constants.ts
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/added_integration_overview_page.tsx
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/create_integration_helpers.ts
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/integrations/components/integration_types.ts
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/home.tsx
  public/components/metrics/top_menu/metrics_export_panel.tsx
  public/components/metrics/top_menu/top_menu.tsx
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/integrations_builder.ts
  server/adaptors/integrations/integrations_manager.ts
  server/adaptors/integrations/types.ts
  server/routes/dsl.ts
  server/routes/integrations/integrations_router.ts
Labels: enhancement, failed backport

#2101 feat: make createAssets API compatible with workspace
  server/routes/getting_started/getting_started_router.ts
Labels: enhancement, backport 2.x

#2099 [Page Header] New page header for notebooks and UI updates
  .cypress/integration/notebooks_test/notebooks.spec.js
  public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/__tests__/note_table.test.tsx
  public/components/notebooks/components/__tests__/notebook.test.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_input.test.tsx.snap
  public/components/notebooks/components/paragraph_components/para_input.tsx
  public/components/notebooks/index.scss
  public/components/trace_analytics/components/dashboard/mode_picker.tsx
  public/plugin.tsx
  public/plugin_headerControl.tsx
Labels: enhancement, backport 2.x

#2103 Page Header] New page header for integrations and UI updates
  public/components/datasources/components/__tests__/data_connection.test.tsx
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_details.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_fields.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/integration.tsx
  public/components/integrations/components/integration_assets_panel.tsx
  public/components/integrations/components/integration_details_panel.tsx
  public/components/integrations/components/integration_fields_panel.tsx
  public/components/integrations/components/integration_header.tsx
  public/components/integrations/components/integration_overview_panel.tsx
  public/components/integrations/components/integration_screenshots_panel.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/plugin_headerControl.tsx
Labels: enhancement, backport 2.x
