Repository opensearch-project/dashboards-observability, pull requests merged in 2024-10, with the labels that each got.

#2187 Add compile step before Cypress runs in CI
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
Labels: maintenance

#2186 [Fit&Finish] Observability overview page
  common/constants/shared.ts
  public/components/overview/home.tsx
Labels: enhancement, backport 2.x

#2177 [Bug] Services Data Picker, UI Fixes
  common/constants/shared.ts
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/metrics/top_menu/top_menu.tsx
  public/components/overview/components/card_configs.tsx
  public/components/overview/components/dashboard_controls.tsx
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/legacy_route_helpers.test.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/legacy_route_helpers.ts
  public/components/trace_analytics/components/common/search_bar.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
  public/plugin.tsx
Labels: bug, backport 2.x

#2196 Update workflows to use real build cache
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
Labels: backport 2.x, infrastructure

#2194 GettingStarted Rework
  common/constants/getting_started_routes.ts
  public/components/getting_started/components/getting_started.tsx
  public/components/getting_started/components/getting_started_collectData.tsx
  public/components/getting_started/components/getting_started_integrationCards.tsx
  public/components/getting_started/components/getting_started_queryAndAnalyze.tsx
  public/components/getting_started/getting_started_artifacts/csv_file/README.md
  public/components/getting_started/getting_started_artifacts/csv_file/assets/fluent-bit-csv-upload-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json
  public/components/getting_started/getting_started_artifacts/csv_file/data/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/.env
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/data-prepper/pipeline.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/docker-complete.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/fluent-bit.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/parsers.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/logs/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/opensearch_dashboards.yml
  public/components/getting_started/getting_started_artifacts/csv_file/info/Getting-Started.md
  public/components/getting_started/getting_started_artifacts/csv_file/schema/csv-logs-1.0.0.mapping.json
  public/components/getting_started/getting_started_artifacts/csv_file/static/data-pepper.png
  public/components/getting_started/getting_started_artifacts/csv_file/static/fluent-bit-getting-started-dashboard.png
  public/components/getting_started/getting_started_artifacts/csv_file/static/fluentbit.png
  public/components/getting_started/getting_started_artifacts/csv_file/static/logo.png
  public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/golang_client/static/logo.svg
  public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/java_client/static/logo.svg
  public/components/getting_started/getting_started_artifacts/nginx/nginx-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-logs.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-metrics.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-traces.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/static/logo.png
  public/components/getting_started/getting_started_artifacts/otel-services/static/logo.svg
  public/components/getting_started/getting_started_artifacts/python_client/python_client-1.0.0.json
  public/components/getting_started/home.tsx
  public/index.scss
  server/routes/getting_started/assets/fluent-bit-csv-upload-1.0.0.ndjson
  server/routes/getting_started/assets/golang-tutorial-1.0.0.ndjson
  server/routes/getting_started/assets/java-tutorial-1.0.0.ndjson
  server/routes/getting_started/assets/nginx-1.0.0.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0-Logs.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0-Metrics.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0-Traces.ndjson
  server/routes/getting_started/assets/python-tutorial-1.0.0.ndjson
  server/routes/getting_started/getting_started_router.ts
  server/routes/getting_started/helper.ts
Labels: enhancement, backport 2.x

#2202 [Backport 2.x] GettingStarted Rework (#2194)
  common/constants/getting_started_routes.ts
  public/components/getting_started/components/getting_started.tsx
  public/components/getting_started/components/getting_started_collectData.tsx
  public/components/getting_started/components/getting_started_integrationCards.tsx
  public/components/getting_started/components/getting_started_queryAndAnalyze.tsx
  public/components/getting_started/getting_started_artifacts/csv_file/README.md
  public/components/getting_started/getting_started_artifacts/csv_file/assets/fluent-bit-csv-upload-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json
  public/components/getting_started/getting_started_artifacts/csv_file/data/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/.env
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/data-prepper/pipeline.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/docker-complete.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/fluent-bit.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/parsers.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/logs/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/opensearch_dashboards.yml
  public/components/getting_started/getting_started_artifacts/csv_file/info/Getting-Started.md
  public/components/getting_started/getting_started_artifacts/csv_file/schema/csv-logs-1.0.0.mapping.json
  public/components/getting_started/getting_started_artifacts/csv_file/static/data-pepper.png
  public/components/getting_started/getting_started_artifacts/csv_file/static/fluent-bit-getting-started-dashboard.png
  public/components/getting_started/getting_started_artifacts/csv_file/static/fluentbit.png
  public/components/getting_started/getting_started_artifacts/csv_file/static/logo.png
  public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/golang_client/static/logo.svg
  public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/java_client/static/logo.svg
  public/components/getting_started/getting_started_artifacts/nginx/nginx-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-logs.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-metrics.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-traces.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/static/logo.png
  public/components/getting_started/getting_started_artifacts/otel-services/static/logo.svg
  public/components/getting_started/getting_started_artifacts/python_client/python_client-1.0.0.json
  public/components/getting_started/home.tsx
  public/index.scss
  server/routes/getting_started/assets/fluent-bit-csv-upload-1.0.0.ndjson
  server/routes/getting_started/assets/golang-tutorial-1.0.0.ndjson
  server/routes/getting_started/assets/java-tutorial-1.0.0.ndjson
  server/routes/getting_started/assets/nginx-1.0.0.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0-Logs.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0-Metrics.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0-Traces.ndjson
  server/routes/getting_started/assets/python-tutorial-1.0.0.ndjson
  server/routes/getting_started/getting_started_router.ts
  server/routes/getting_started/helper.ts
Labels: enhancement

#2200 [Feature] Auto trigger schema setup in assets creation flow of get started page
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/getting_started/components/getting_started_collectData.tsx
  public/components/getting_started/components/utils.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  server/routes/getting_started/getting_started_router.ts
  server/routes/getting_started/helper.ts
Labels: enhancement

#2201 Update traces span redirection
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
Labels: bug, backport 2.x

#2205 GettingStarted Fit and Finish
  common/constants/integrations.ts
  public/components/getting_started/components/getting_started_collectData.tsx
  public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/nginx/nginx-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-logs.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-metrics.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0-traces.json
  public/components/getting_started/getting_started_artifacts/python_client/python_client-1.0.0.json
  public/components/integrations/components/added_integration.tsx
  public/components/integrations/components/added_integration_overview_page.tsx
  public/components/integrations/components/available_integration_overview_page.tsx
  public/components/integrations/components/integration.tsx
  public/components/integrations/home.tsx
Labels: enhancement, backport 2.x

#2198 feat: hide default dashboard setting when workspace is enabled
  server/plugin.ts
Labels: enhancement, backport 2.x

#2213 [Bug] [MDS] call to remote cluster has missing else condition
  server/adaptors/metrics/metrics_analytics_adaptor.ts
Labels: bug, backport 2.x

#2210 Observability Overview page rework
  common/constants/overview.ts
  common/utils/core_services.ts
  public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap
  public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
  public/components/integrations/components/available_integration_card_view.tsx
  public/components/integrations/components/available_integration_table.tsx
  public/components/overview/components/__tests__/__snapshots__/add_dashboard_callout.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/dashboard_controls.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/select_dashboard_flyout.test.tsx.snap
  public/components/overview/components/add_dashboard_callout.tsx
  public/components/overview/components/assets/SampleDataDark.png
  public/components/overview/components/assets/SampleDataLight.png
  public/components/overview/components/assets/SelectDashboard.svg
  public/components/overview/components/dashboard_controls.tsx
  public/components/overview/components/select_dashboard_flyout.tsx
  public/components/overview/components/utils.tsx
  public/components/overview/home.tsx
  public/plugin.tsx
  public/plugin_helpers/plugin_overview.tsx
  server/plugin.ts
Labels: enhancement, backport 2.x

#2217 [BUG] Metrics fixes
  public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
Labels: bug, backport 2.x

#2219 [BUG]Re direction fix for associated logs from traces
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/home.tsx
Labels: bug, backport 2.x

#2225 Fixes span to logs redireciton, updates mds label when undefined
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/home.tsx
Labels: bug, backport 2.x

#2222 [MDS][Bug]added changes for de registering plugins not in MDS and changed other…
  server/routes/application_analytics/app_analytics_router.ts
  server/routes/custom_panels/panels_router.ts
  server/routes/event_analytics/event_analytics_router.ts
  server/routes/metrics/metrics_rounter.ts
  server/routes/ppl.ts
  server/routes/trace_analytics_dsl_router.ts
Labels: bug, backport 2.x

#2231 added release-notes for v2.18.0
  release-notes/opensearch-observability.release-notes-2.18.0.0.md
Labels: backport 2.x, v2.18.0, backport 2.18

#2229 [Bug fix] Traces/Services bugfixes and UI update
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filters.tsx
  public/components/trace_analytics/components/common/search_bar.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/home.tsx
Labels: bug, backport 2.x
