Repository opensearch-project/dashboards-observability, pull requests merged in 2024-11, with the labels that each got.

#2238 [Traces] Return 503 if opensearch calls failed
  server/plugin.ts
  server/routes/dsl.ts
  server/routes/index.ts
  server/services/queryService.ts
Labels: bug, backport 2.x, mds-2.18.0

#2240 Fix mds ref update on integration assets
  public/components/integrations/components/create_integration_helpers.ts
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/integrations_builder.ts
Labels: bug, backport 2.x, mds-2.18.0

#2242 [Bug fix] Metrics datasource
  public/components/metrics/index.tsx
  public/components/metrics/sidebar/sidebar.tsx
Labels: bug, backport 2.x, mds-2.18.0

#2241 Use savedObjects client to fetch notebook visualizations
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: bug, backport 2.x, mds-2.18.0

#2249 [Manual Backport 2.x] Use savedObjects client to fetch notebook visualizations (#2241)
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: bug

#2246 Replace index mapping with field caps API for trace filters
  common/constants/shared.ts
  public/components/common/types.ts
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/helper_functions.test.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/home.tsx
  public/services/requests/dsl.ts
  server/routes/dsl.ts
  test/constants.ts
Labels: bug, backport 2.x, mds-2.18.0

#2237 Overview page add state for missing data source
  common/constants/shared.ts
  public/components/overview/components/__tests__/__snapshots__/add_datasource_callout.test.tsx.snap
  public/components/overview/components/__tests__/__snapshots__/dashboard_controls.test.tsx.snap
  public/components/overview/components/__tests__/add_datasource_callout.test.tsx
  public/components/overview/components/__tests__/dashboard_controls.test.tsx
  public/components/overview/components/add_dashboard_callout.tsx
  public/components/overview/components/add_datasource_callout.tsx
  public/components/overview/components/dashboard_controls.tsx
  public/components/overview/components/select_dashboard_flyout.tsx
  public/components/overview/home.tsx
  public/plugin_helpers/plugin_overview.tsx
Labels: enhancement, backport 2.x, mds-2.18.0

#2251 [Cypress Updates] Trace analytics updates
  .cypress/integration/trace_analytics_test/trace_analytics_dashboard.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_edit_popover.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filter_edit_popover.tsx
  public/components/trace_analytics/components/common/filters/filters.tsx
Labels: backport 2.x, maintenance

#2230 Service map updates
  public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map.test.tsx.snap
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/common/plots/service_map_node_details.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  test/constants.ts
Labels: enhancement, backport 2.x, mds-2.18.0

#2255 [Cypress Updates] Notebooks updates
  .cypress/integration/notebooks_test/notebooks.spec.js
  .cypress/utils/constants.js
Labels: enhancement, backport 2.x

#2259 Separate uploaded cypress artifacts for actions/upload-artifact@v4
  .github/workflows/integration-tests-workflow.yml
Labels: backport 2.x, maintenance

#2265 Remove dco and update artifact action to v4
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/dco.yml
Labels: enhancement, infrastructure

#2263 Fix flaky render of spans table tests
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  public/components/trace_analytics/components/common/plots/service_dependencies_table.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
Labels: backport 2.x, maintenance
