Repository opensearch-project/dashboards-observability, pull requests merged in 2024-07, with the labels that each got.

#1939 fix minor issues in query assist UI
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/common/search/query_area.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
Labels: backport 2.x

#1940 updated java version from 11 to 21
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
Labels: maintenance

#1943 Adding attributefilter field to app analytics
  public/components/application_analytics/home.tsx
Labels: bug, backport main

#1942 [Bug Fix] Add mds support for routers and fix the missing `callAsCurrentUser`
  server/routes/data_connections/data_connections_router.ts
  server/routes/dsl.ts
  server/routes/index.ts
Labels: enhancement, backport 2.x

#1926 [Navigation] Register all plugins to NavGroups
  common/constants/shared.ts
  common/utils/set_nav_bread_crumbs.ts
  public/components/app.tsx
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/components/create.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/index.tsx
  public/components/metrics/index.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
  public/plugin.tsx
  public/plugin_nav.tsx
Labels: enhancement, backport 2.x

#1948 [Backport 2.x][Navigation] Register all plugins to NavGroups (#1926)
  common/constants/shared.ts
  common/utils/set_nav_bread_crumbs.ts
  public/components/app.tsx
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/application_analytics/components/app_table.tsx
  public/components/application_analytics/components/application.tsx
  public/components/application_analytics/components/create.tsx
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/index.tsx
  public/components/metrics/index.tsx
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
  public/plugin.tsx
  public/plugin_nav.tsx
Labels: enhancement

#1937 added changes for moving notebooks to .kibana
  .cypress/integration/notebooks_test/notebooks.spec.js
  common/types/notebooks.ts
  common/types/observability_saved_object_attributes.ts
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/__tests__/note_table.test.tsx
  public/components/notebooks/components/__tests__/notebook.test.tsx
  public/components/notebooks/components/helpers/default_parser.tsx
  public/components/notebooks/components/helpers/notebooks_parser.tsx
  public/components/notebooks/components/main.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/paragraphs.test.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
  server/adaptors/notebooks/default_backend.ts
  server/adaptors/notebooks/notebook_adaptor.ts
  server/adaptors/notebooks/saved_objects_notebooks_router.tsx
  server/adaptors/notebooks/saved_objects_paragraphs_router.tsx
  server/common/helpers/notebooks/default_notebook_schema.ts
  server/common/helpers/notebooks/sample_notebooks.ts
  server/common/helpers/notebooks/wreck_requests.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/notebooks/noteRouter.ts
  server/routes/notebooks/paraRouter.ts
  server/routes/notebooks/sqlRouter.ts
  server/routes/notebooks/vizRouter.ts
  server/saved_objects/observability_saved_object.ts
  server/services/queryService.ts
  test/notebooks_constants.ts
Labels: enhancement, backport 2.x

#1953 Version-decoupling for Observability
  common/utils/shared.ts
  opensearch_dashboards.json
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap
  public/components/metrics/index.tsx
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
Labels: enhancement, backport 2.x, backport 2.16

#1963 replace dashboards with the getting started dashboards
  server/adaptors/integrations/__data__/repository/otel-services/assets/otel-index-patterns-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/otel-services/otel-services-1.0.0.json
Labels: enhancement, backport 2.x, integrations, backport 2.16

#1971 UX copy changes for Notebooks with MDS
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: bug, backport 2.x, backport 2.16

#1972 Unregister observability datasource from old and new nav group
  public/plugin.tsx
Labels: bug, backport 2.x, backport 2.16

#1977 [Bugfix] Add toast message for getting started / Fix Nav Bug for Traces
  public/components/getting_started/components/getting_started_collectData.tsx
  public/components/getting_started/components/utils.tsx
  public/components/trace_analytics/components/dashboard/dashboard_content.tsx
Labels: bug, backport 2.x, backport 2.16

#1981 [Bug] Added upgrade button in callout for legacy notebooks
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/__tests__/notebook.test.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
Labels: bug, backport 2.x, backport 2.16

#1980 Add 2.16 notes
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
Labels: backport 2.x, maintenance, backport 2.16

#1987 [Bug] Fix CVEs for ag-grid, ws and braces packages
  package.json
  yarn.lock
Labels: backport 2.x, maintenance, backport 2.16

#1989 [Bug] CVE fix for ag
  package.json
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
  yarn.lock
Labels: maintenance

#1990 Backport 2.x Fix CVEs for ag-grid, ws and braces packages
  package.json
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
  yarn.lock
Labels: maintenance

#1992 [Feature] Multi-data Source Support for Integrations
  public/components/integrations/components/added_integration_overview_page.tsx
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/integration_types.ts
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/home.tsx
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
Labels: enhancement, backport 2.x, v2.16.0

#1991 Backport 2.16 Fix CVEs for ag-grid, ws and braces packages
  package.json
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
  yarn.lock
Labels: maintenance, v2.16.0

#1993 [BUG] missed files for integration-mds setup
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/integrations/components/setup_integration.tsx
Labels: bug

#1996 [Backport 2.x] backport of integrations for MDS support
  public/components/datasources/components/manage/integrations/installed_integrations_table.tsx
  public/components/integrations/components/added_integration_overview_page.tsx
  public/components/integrations/components/added_integration_table.tsx
  public/components/integrations/components/integration_types.ts
  public/components/integrations/components/setup_integration.tsx
  public/components/integrations/components/setup_integration_inputs.tsx
  public/components/integrations/home.tsx
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
Labels: enhancement

#1998 [BUG] fix redirection url in saved objects management page for notebooks
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
  server/saved_objects/observability_saved_object.ts
Labels: bug, backport 2.x, backport 2.16

#2001 [Bug] Remove ag grid package
  package.json
  public/components/event_analytics/explorer/visualizations/workspace_panel/workspace_panel.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/data_table.test.tsx.snap
  public/components/visualizations/charts/__tests__/data_table.test.tsx
  public/components/visualizations/charts/data_table/data_table.tsx
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
  yarn.lock
Labels: bug, backport 2.x, backport 2.16

#2005 [Backport main] Adding attributefilter field to app analytics (#1943)
  public/components/application_analytics/home.tsx
Labels: bug

#2003 [Backport 2.16] [Bug] Remove ag grid package (#2001)
  package.json
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/event_analytics/explorer/visualizations/workspace_panel/workspace_panel.tsx
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/visualizations/charts/__tests__/__snapshots__/data_table.test.tsx.snap
  public/components/visualizations/charts/__tests__/data_table.test.tsx
  public/components/visualizations/charts/data_table/data_table.tsx
  release-notes/dashboards-observability.release-notes-2.16.0.0.md
  yarn.lock
Labels: maintenance

#2006 [Bug] Trace Analytics bug fix for local cluster being rendered
  public/components/application_analytics/components/application.tsx
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
Labels: bug, backport 2.x, backport 2.16

#2009 [Backport 2.16] Trace Analytics bug fix for local cluster being rendered (#2006)
  public/components/application_analytics/components/application.tsx
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
Labels: bug

#2008 [Backport 2.x] Trace Analytics bug fix for local cluster being rendered (#2006)
  public/components/application_analytics/components/application.tsx
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/home.tsx
Labels: bug

#2012 update getting-started links to match recent catalog PR merges
  public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/.env
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/docker-complete.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/fluent-bit.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/parsers.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/logs/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/opensearch_dashboards.yml
  public/components/getting_started/getting_started_artifacts/csv_file/info/Getting-Started.md
  public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/nginx/nginx-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0.json
  public/components/getting_started/getting_started_artifacts/python_client/python_client-1.0.0.json
Labels: bug, backport main, backport 2.16

#2016 [Bug] Getting Started update patterns created
  public/components/getting_started/getting_started_artifacts/csv_file/assets/fluent-bit-csv-upload-1.0.0.ndjson
  public/components/getting_started/getting_started_artifacts/otel-services/assets/otel-index-patterns-1.0.0.ndjson
  server/routes/getting_started/assets/fluent-bit-csv-upload-1.0.0.ndjson
  server/routes/getting_started/assets/otel-index-patterns-1.0.0.ndjson
Labels: backport 2.x, backport main, backport 2.16

#2017 Fix docker links & index patterns names
  public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json
  public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
Labels: bug, backport 2.x, backport main, backport 2.16

#2020 [Backport main] Getting started changes (#2012 and #2017)
  public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/.env
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/docker-complete.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit.yml
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/fluent-bit.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/fluent-bit/parsers.conf
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/logs/logs.csv
  public/components/getting_started/getting_started_artifacts/csv_file/getting-started/opensearch_dashboards.yml
  public/components/getting_started/getting_started_artifacts/csv_file/info/Getting-Started.md
  public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
  public/components/getting_started/getting_started_artifacts/nginx/nginx-1.0.0.json
  public/components/getting_started/getting_started_artifacts/otel-services/otel-services-1.0.0.json
  public/components/getting_started/getting_started_artifacts/python_client/python_client-1.0.0.json
Labels: bug
