Repository opensearch-project/dashboards-observability, pull requests merged in 2024-01, with the labels that each got.

#1315 [CI/CD] Add FTR workflow for dashboards observability
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
Labels: testing

#1331 Pull integrations integration test fixes to 2.x
  .cypress/integration/integrations_test/integrations.spec.js
  public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap
  public/components/integrations/components/setup_integration.tsx
Labels: maintenance

#1335 Correct learn more link in log explorer home page
  common/constants/explorer.ts
Labels: backport 2.x

#1332 Fix lints for integrations.spec.js and setup_integrations.ts
  .cypress/integration/integrations_test/integrations.spec.js
  public/components/integrations/components/setup_integration.tsx
Labels: maintenance

#1296 Removes Zeppelin code and docs
  common/constants/notebooks.ts
  public/components/notebooks/components/helpers/__tests__/sampleZeppelinNotebooks.tsx
  public/components/notebooks/components/helpers/__tests__/zeppelin_parser.test.tsx
  public/components/notebooks/components/helpers/zeppelin_parser.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/docs/dev/Zeppelin_backend_adaptor.md
  public/components/notebooks/docs/dev/images/zeppelin_architecture.png
  public/components/notebooks/docs/example_notebooks/zeppelin/Introduction Notebook-Zeppelin.json
  public/components/notebooks/docs/example_notebooks/zeppelin/Log Analysis-Zeppelin.json
  public/components/notebooks/docs/poc/OpenSearch_Dashboards_Embeddable_Documentation.md
  public/components/notebooks/docs/poc/Zeppelin_OpenSearch_Storage.md
  public/components/notebooks/docs/poc/docs/Zeppelin_OpenSearch_Storage.md
  public/components/notebooks/docs/poc/zeppelin-patch
  public/components/notebooks/docs/poc/zeppelin/zeppelin-plugins/notebookrepo/opensearch/pom.xml
  public/components/notebooks/docs/poc/zeppelin/zeppelin-plugins/notebookrepo/opensearch/src/main/java/org/apache/zeppelin/notebook/repo/OpenSearchNotebookRepo.java
  server/adaptors/notebooks/index.ts
  server/adaptors/notebooks/zeppelin_backend.ts
Labels: backport 2.x, maintenance

#1334 [Backport 2.x] Add FTR workflow for dashboards observability
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
Labels: infrastructure

#1307 Notebook jest updates
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/__tests__/note_table.test.tsx
  public/components/notebooks/components/__tests__/notebook.test.tsx
  public/components/notebooks/components/helpers/__tests__/default_parser.test.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/para_input.test.tsx
  public/components/notebooks/components/paragraph_components/__tests__/para_output.test.tsx
  public/components/notebooks/components/paragraph_components/__tests__/paragraphs.test.tsx
  public/components/notebooks/components/paragraph_components/para_output.tsx
  public/components/notebooks/components/paragraph_components/para_query_grid.tsx
  test/notebooks_constants.ts
Labels: backport 2.x, maintenance

#1342 Sync dependencies with latest versions
  package.json
  yarn.lock
Labels: backport 2.x, maintenance

#1323 [Enhancement/Fix] Refactor datasources cypress tests
  .cypress/integration/datasources_test/datasources.spec.js
  .cypress/integration/datasources_test/datasources_basic_ui.spec.js
  .cypress/utils/constants.js
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/lint.yml
  cypress.config.js
Labels: enhancement, backport 2.x, testing

#1325 Merge feature/explorer-query-assistant to main
  common/constants/data_sources.ts
  common/constants/explorer.ts
  common/constants/query_assist.ts
  common/constants/shared.ts
  opensearch_dashboards.json
  public/.DS_Store
  public/components/common/live_tail/live_tail_button.tsx
  public/components/common/search/date_picker.tsx
  public/components/common/search/query_area.tsx
  public/components/common/search/query_assist_summarization.tsx
  public/components/common/search/search.tsx
  public/components/datasources/icons/query-assistant-logo.svg
  public/components/event_analytics/__tests__/__snapshots__/no_results.test.tsx.snap
  public/components/event_analytics/__tests__/no_results.test.tsx
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/query_assist/__tests__/hooks.test.ts
  public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx
  public/components/event_analytics/explorer/query_assist/hooks.ts
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/sidebar.test.tsx
  public/components/event_analytics/explorer/sidebar/field.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.tsx
  public/components/event_analytics/home/home.tsx
  public/components/event_analytics/hooks/use_fetch_events.ts
  public/components/event_analytics/hooks/use_fetch_patterns.ts
  public/components/event_analytics/hooks/use_fetch_visualizations.ts
  public/components/event_analytics/redux/reducers/fetch_reducers.ts
  public/components/event_analytics/redux/reducers/index.ts
  public/components/event_analytics/redux/slices/query_assistant_summarization_slice.ts
  public/components/event_analytics/redux/slices/query_result_slice.ts
  public/components/event_analytics/redux/slices/query_slice.ts
  public/components/event_analytics/redux/slices/search_meta_data_slice.ts
  public/framework/core_refs.ts
  public/framework/redux/reducers/index.ts
  public/index.ts
  public/plugin.ts
  public/services/data_fetchers/ppl/ppl_data_fetcher.ts
  server/common/helpers/query_assist/__tests__/generate_field_context.test.ts
  server/common/helpers/query_assist/generate_field_context.ts
  server/index.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/query_assist/routes.ts
Labels: enhancement

#1359 support searching agent by name
  server/index.ts
  server/routes/query_assist/routes.ts
  server/routes/query_assist/utils/__tests__/agents.test.ts
  server/routes/query_assist/utils/agents.ts
Labels: enhancement

#1314 Add otel metrics
  .cypress/integration/metrics_analytics_test/metrics_analytics.spec.js
  .cypress/integration/panels_test/panels.spec.ts
  .cypress/utils/metrics_constants.js
  common/constants/metrics.ts
  common/constants/shared.ts
  common/types/explorer.ts
  common/types/metrics.ts
  public/components/application_analytics/helpers/utils.tsx
  public/components/common/query_utils/__tests__/query_utils.test.tsx
  public/components/common/query_utils/index.ts
  public/components/custom_panels/custom_panel_view.tsx
  public/components/custom_panels/helpers/utils.tsx
  public/components/custom_panels/panel_modules/panel_grid/panel_grid.tsx
  public/components/custom_panels/panel_modules/panel_grid/panel_grid_so.tsx
  public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap
  public/components/event_analytics/home/saved_objects_table.tsx
  public/components/event_analytics/utils/utils.tsx
  public/components/metrics/helpers/utils.tsx
  public/components/metrics/index.tsx
  public/components/metrics/redux/slices/__tests__/metric_slice.test.tsx
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/metrics/sidebar/__tests__/sidebar.test.tsx
  public/components/metrics/sidebar/data_source_picker.tsx
  public/components/metrics/sidebar/index_picker.tsx
  public/components/metrics/sidebar/metric_name.tsx
  public/components/metrics/sidebar/metrics_accordion.tsx
  public/components/metrics/sidebar/sidebar.tsx
  public/components/metrics/top_menu/metrics_export.tsx
  public/components/metrics/view/metrics_grid.tsx
  public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap
  public/components/visualizations/charts/lines/line.tsx
  public/components/visualizations/saved_object_visualization.tsx
  public/components/visualizations/visualization.tsx
  public/components/visualizations/visualization_chart.tsx
  public/embeddable/observability_embeddable.tsx
  public/services/saved_objects/event_analytics/saved_objects.ts
  public/services/saved_objects/saved_object_client/osd_saved_objects/osd_saved_object_client.ts
  public/services/saved_objects/saved_object_client/osd_saved_objects/saved_searches.ts
  public/services/saved_objects/saved_object_client/osd_saved_objects/saved_visualization.ts
  public/services/saved_objects/saved_object_client/ppl/ppl_client.ts
  public/services/saved_objects/saved_object_client/ppl/saved_visualization.ts
  public/services/saved_objects/saved_object_client/saved_objects_actions.ts
  server/adaptors/custom_panels/custom_panel_adaptor.ts
  server/adaptors/metrics/metrics_analytics_adaptor.ts
  server/routes/event_analytics/event_analytics_router.ts
  server/routes/metrics/metrics_rounter.ts
Labels: enhancement, backport 2.x

#1360 Fix test failures from query assistant
  common/constants/shared.ts
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/common/search/__tests__/search.test.tsx
  public/components/common/search/date_picker.tsx
  public/components/common/search/search.tsx
  public/components/event_analytics/redux/slices/query_slice.ts
  public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
Labels: maintenance

#1288 JSON Catalog Reader for Integrations
  server/adaptors/integrations/__test__/builder.test.ts
  server/adaptors/integrations/__test__/json_repository.test.ts
  server/adaptors/integrations/__test__/local_fs_repository.test.ts
  server/adaptors/integrations/__test__/manager.test.ts
  server/adaptors/integrations/integrations_builder.ts
  server/adaptors/integrations/repository/__test__/integration_reader.test.ts
  server/adaptors/integrations/repository/__test__/json_data_adaptor.test.ts
  server/adaptors/integrations/repository/__test__/repository.test.ts
  server/adaptors/integrations/repository/__test__/utils.test.ts
  server/adaptors/integrations/repository/catalog_data_adaptor.ts
  server/adaptors/integrations/repository/fs_data_adaptor.ts
  server/adaptors/integrations/repository/integration.ts
  server/adaptors/integrations/repository/integration_reader.ts
  server/adaptors/integrations/repository/json_data_adaptor.ts
  server/adaptors/integrations/repository/repository.ts
  server/adaptors/integrations/repository/utils.ts
  server/adaptors/integrations/types.ts
  server/adaptors/integrations/validators.ts
Labels: enhancement, integrations

#1233 [DOC]Revise and edit PPL in-product documentation
  public/components/common/helpers/ppl_docs/commands/dedup.ts
  public/components/common/helpers/ppl_docs/commands/eval.ts
  public/components/common/helpers/ppl_docs/commands/fields.ts
  public/components/common/helpers/ppl_docs/commands/head.ts
  public/components/common/helpers/ppl_docs/commands/parse.ts
  public/components/common/helpers/ppl_docs/commands/rare.ts
  public/components/common/helpers/ppl_docs/commands/rename.ts
  public/components/common/helpers/ppl_docs/commands/search.ts
  public/components/common/helpers/ppl_docs/commands/sort.ts
  public/components/common/helpers/ppl_docs/commands/stats.ts
  public/components/common/helpers/ppl_docs/commands/syntax.ts
  public/components/common/helpers/ppl_docs/commands/top.ts
  public/components/common/helpers/ppl_docs/commands/where.ts
  public/components/common/helpers/ppl_docs/functions/condition.ts
  public/components/common/helpers/ppl_docs/functions/datetime.ts
  public/components/common/helpers/ppl_docs/functions/full_text_search.ts
  public/components/common/helpers/ppl_docs/functions/math.ts
  public/components/common/helpers/ppl_docs/functions/string.ts
  public/components/common/helpers/ppl_docs/language_structure/datatypes.ts
  public/components/common/helpers/ppl_docs/language_structure/identifiers.ts
  public/components/common/helpers/ppl_docs/overview.tsx
Labels: documentation, backport 2.x

#1370 Update jest snapshot and fix failing build
  public/components/common/helpers/ppl_docs/commands/syntax.ts
  public/dependencies/components/__snapshots__/data_grid_container.test.tsx.snap
Labels: backport 2.x, maintenance

#1372 fix syntax error from #1233
  public/components/common/helpers/ppl_docs/commands/syntax.ts
Labels: backport main, maintenance

#1367 Update notebooks snapshots and cypress
  .cypress/integration/notebooks_test/notebooks.spec.js
  .cypress/utils/constants.js
  public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap
  public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
  public/components/notebooks/components/__tests__/note_table.test.tsx
  public/components/notebooks/components/note_table.tsx
  public/components/notebooks/components/notebook.tsx
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_input.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/notebooks/components/paragraph_components/para_input.tsx
  public/components/notebooks/components/paragraph_components/para_output.tsx
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
Labels: backport 2.x, maintenance

#1376 (query assist) support option to disable summary
  common/constants/shared.ts
  public/components/common/search/__tests__/search.test.tsx
  public/components/common/search/query_assist_summarization.tsx
  public/components/common/search/search.tsx
  public/components/common/search/sql_search.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/explorer/sidebar/__tests__/sidebar.test.tsx
  public/components/event_analytics/explorer/sidebar/field.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.tsx
  public/components/event_analytics/home/home.tsx
  public/components/event_analytics/hooks/use_fetch_patterns.ts
  public/components/event_analytics/hooks/use_fetch_visualizations.ts
  public/components/event_analytics/redux/slices/query_slice.ts
  public/components/event_analytics/redux/slices/search_meta_data_slice.ts
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/sidebar.tsx
  public/framework/core_refs.ts
  public/plugin.ts
  public/services/data_fetchers/ppl/ppl_data_fetcher.ts
  server/index.ts
  server/plugin.ts
  server/routes/query_assist/routes.ts
Labels: enhancement

#1379 (query assist) enforce timerange to `QUERY_ASSIST_START_TIME`
  public/components/common/search/query_area.tsx
  public/components/common/search/search.tsx
  public/components/event_analytics/explorer/query_assist/input.tsx
Labels: bug

#1369 [2.x] Backport query assist
  common/constants/data_sources.ts
  common/constants/explorer.ts
  common/constants/query_assist.ts
  common/constants/shared.ts
  opensearch_dashboards.json
  public/.DS_Store
  public/components/common/live_tail/live_tail_button.tsx
  public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap
  public/components/common/search/__tests__/search.test.tsx
  public/components/common/search/date_picker.tsx
  public/components/common/search/query_area.tsx
  public/components/common/search/query_assist_summarization.tsx
  public/components/common/search/search.tsx
  public/components/common/search/sql_search.tsx
  public/components/datasources/icons/query-assistant-logo.svg
  public/components/event_analytics/__tests__/__snapshots__/no_results.test.tsx.snap
  public/components/event_analytics/__tests__/no_results.test.tsx
  public/components/event_analytics/explorer/datasources/datasources_selection.tsx
  public/components/event_analytics/explorer/events_views/data_grid.tsx
  public/components/event_analytics/explorer/explorer.tsx
  public/components/event_analytics/explorer/no_results.tsx
  public/components/event_analytics/explorer/query_assist/__tests__/hooks.test.ts
  public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx
  public/components/event_analytics/explorer/query_assist/hooks.ts
  public/components/event_analytics/explorer/query_assist/input.tsx
  public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
  public/components/event_analytics/explorer/sidebar/__tests__/sidebar.test.tsx
  public/components/event_analytics/explorer/sidebar/field.tsx
  public/components/event_analytics/explorer/sidebar/sidebar.tsx
  public/components/event_analytics/home/home.tsx
  public/components/event_analytics/hooks/use_fetch_events.ts
  public/components/event_analytics/hooks/use_fetch_patterns.ts
  public/components/event_analytics/hooks/use_fetch_visualizations.ts
  public/components/event_analytics/redux/reducers/fetch_reducers.ts
  public/components/event_analytics/redux/reducers/index.ts
  public/components/event_analytics/redux/slices/query_assistant_summarization_slice.ts
  public/components/event_analytics/redux/slices/query_result_slice.ts
  public/components/event_analytics/redux/slices/query_slice.ts
  public/components/event_analytics/redux/slices/search_meta_data_slice.ts
  public/components/metrics/redux/slices/metrics_slice.ts
  public/components/metrics/sidebar/sidebar.tsx
  public/framework/core_refs.ts
  public/framework/redux/reducers/index.ts
  public/index.ts
  public/plugin.ts
  public/services/data_fetchers/ppl/ppl_data_fetcher.ts
  server/common/helpers/query_assist/__tests__/generate_field_context.test.ts
  server/common/helpers/query_assist/generate_field_context.ts
  server/index.ts
  server/plugin.ts
  server/routes/index.ts
  server/routes/query_assist/routes.ts
  server/routes/query_assist/utils/__tests__/agents.test.ts
  server/routes/query_assist/utils/agents.ts
Labels: enhancement

#1364 Remove redundant git add from lint-staged
  package.json
Labels: maintenance

#1378 improve lint workflow to avoid fast fail
  .github/workflows/lint.yml
Labels: enhancement, backport 2.x

#1387 Optimize images in integrations repository
  server/adaptors/integrations/__data__/repository/apache/static/dashboard1.png
  server/adaptors/integrations/__data__/repository/apache/static/logo.png
  server/adaptors/integrations/__data__/repository/aws_cloudfront/static/dashboard.png
  server/adaptors/integrations/__data__/repository/aws_cloudfront/static/logo.png
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/static/dashboard.png
  server/adaptors/integrations/__data__/repository/aws_cloudtrail/static/logo.png
  server/adaptors/integrations/__data__/repository/aws_elb/static/dashboard1.png
  server/adaptors/integrations/__data__/repository/aws_elb/static/logo.svg
  server/adaptors/integrations/__data__/repository/aws_rds/static/aws-rds-icon.png
  server/adaptors/integrations/__data__/repository/aws_rds/static/dashboard.png
  server/adaptors/integrations/__data__/repository/aws_s3/static/dashboard.png
  server/adaptors/integrations/__data__/repository/aws_s3/static/logo.png
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/static/dashboard1.png
  server/adaptors/integrations/__data__/repository/aws_vpc_flow/static/logo.svg
  server/adaptors/integrations/__data__/repository/aws_waf/static/dashboard.png
  server/adaptors/integrations/__data__/repository/aws_waf/static/logo.jpg
  server/adaptors/integrations/__data__/repository/haproxy/static/dashboard1.png
  server/adaptors/integrations/__data__/repository/haproxy/static/dashboard2.png
  server/adaptors/integrations/__data__/repository/haproxy/static/logo.svg
  server/adaptors/integrations/__data__/repository/k8s/static/dashboard.png
  server/adaptors/integrations/__data__/repository/k8s/static/logo.png
  server/adaptors/integrations/__data__/repository/nginx/static/dashboard1.png
  server/adaptors/integrations/__data__/repository/nginx/static/dashboard2.png
  server/adaptors/integrations/__data__/repository/nginx/static/logo.svg
  server/adaptors/integrations/__test__/json_repository.test.ts
Labels: backport 2.x, integrations, maintenance

#1390 Fix trace link in event viewer
  public/components/event_analytics/explorer/events_views/docViewer.tsx
Labels: bug, backport 2.x
