Repository opensearch-project/dashboards-observability, pull requests merged in 2025-01, with the labels that each got.

#2304 [Backport 2.x] Update latest github links in maintainer doc
  MAINTAINERS.md
Labels: bug

#2305 Add stalled PRs workflow
  .github/workflows/stalled.yml
Labels: infrastructure

#2298 Traces custom source - Bug Fixes
  public/components/trace_analytics/components/common/__tests__/helper_functions.test.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/dashboard/mode_picker.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/traces_table.test.tsx
  public/components/trace_analytics/components/traces/services_list.tsx
  public/components/trace_analytics/components/traces/trace_table_helpers.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/requests/services_request_handler.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: bug, backport 2.x

#2306 Downgrade cypress to 12.17.4
  package.json
  yarn.lock
Labels: backport 2.x, maintenance

#2299 [Doc] SOP for Integration and Vended Dashabords Setup
  docs/integrations/doc_assets/dashboard_export.png
  docs/integrations/doc_assets/dashboard_import.png
  docs/integrations/doc_assets/index_pattern_creation.png
  docs/integrations/doc_assets/index_pattern_time_field.png
  docs/integrations/doc_assets/visualization_configuration.png
  docs/integrations/doc_assets/visualization_index_pattern_selection.png
  docs/integrations/doc_assets/visualization_type_selection.png
  docs/integrations/setup.md
Labels: documentation, integrations

#2310 Traces/Services - Query optimization / UI setting / Bugfix
  .cypress/utils/constants.js
  common/constants/trace_analytics.ts
  public/components/trace_analytics/components/common/__tests__/__snapshots__/helper_functions.test.tsx.snap
  public/components/trace_analytics/components/common/__tests__/helper_functions.test.tsx
  public/components/trace_analytics/components/common/custom_index_flyout.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/services/__tests__/services_table.test.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_table.tsx
  public/components/trace_analytics/components/traces/trace_table_helpers.tsx
  public/components/trace_analytics/home.tsx
  public/components/trace_analytics/requests/queries/services_queries.ts
  public/components/trace_analytics/requests/services_request_handler.ts
  server/plugin_helper/register_settings.ts
Labels: bug, backport 2.x, maintenance

#2315 Remove redundant traces call for related services
  common/constants/trace_analytics.ts
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/requests/services_request_handler.ts
Labels: bug, backport 2.x, traces

#2318 [Enhancement] Remove the maxFilesPerTrigger limits for VPC MV
  server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/aws_vpc_live_stream_mv_schema-1.0.0.sql
Labels: enhancement, backport 2.x, integrations

#2322 [CVE-2024-21538] Bump cross-spawn to 7.0.5
  package.json
  yarn.lock
Labels: backport 2.x, maintenance, backport 2.19

#2324 [Backport 2.19] [CVE-2024-21538] Bump cross-spawn to 7.0.5 (#2322)
  package.json
  yarn.lock
Labels: maintenance

#2323 [Backport 2.x] [CVE-2024-21538] Bump cross-spawn to 7.0.5 (#2322)
  package.json
  yarn.lock
Labels: maintenance

#2321 Traces - Filter Adjustment and DataGrid abstraction
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_edit_popover.test.tsx.snap
  public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_helpers.test.tsx.snap
  public/components/trace_analytics/components/common/filters/filter_edit_popover.tsx
  public/components/trace_analytics/components/common/filters/filter_helpers.tsx
  public/components/trace_analytics/components/common/filters/filters.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx
  public/components/trace_analytics/components/common/shared_components/sharedComponents.scss
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/index.scss
Labels: bug, backport 2.x, traces, backport 2.19

#2328 [CVE-2024-55565] Bump nanoid to 3.3.8
  package.json
  yarn.lock
Labels: backport 2.x, maintenance, backport 2.19
