Repository opensearch-project/dashboards-observability, pull requests merged in 2025-03, with the labels that each got.

#2367 ServiceMap Query Optimizations
  public/components/trace_analytics/requests/queries/services_queries.ts
  public/components/trace_analytics/requests/services_request_handler.ts
Labels: backport 2.x, maintenance

#2368 Trace Groups Optimization - Remove duplicate filters
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/dashboard_content.tsx
  public/components/trace_analytics/components/dashboard/dashboard_table.tsx
Labels: bug, backport 2.x

#2369 [Bug] Traces redirection while QA enabled
  public/components/common/search/query_area.tsx
  public/components/common/search/search.tsx
Labels: bug, backport 2.x

#2376 Improve the test results for Integrations internals
  .eslintrc.js
  server/adaptors/integrations/__test__/custom_expects.ts
  server/adaptors/integrations/__test__/json_repository.test.ts
  server/adaptors/integrations/__test__/local_fs_repository.test.ts
  server/adaptors/integrations/repository/__test__/integration_reader.test.ts
  server/adaptors/integrations/repository/integration_reader.ts
Labels: backport 2.x, infrastructure, maintenance

#2378 [Manual Backport] Backport 2376 to 2.x
  .eslintrc.js
  server/adaptors/integrations/__test__/custom_expects.ts
  server/adaptors/integrations/__test__/json_repository.test.ts
  server/adaptors/integrations/__test__/local_fs_repository.test.ts
  server/adaptors/integrations/repository/__test__/integration_reader.test.ts
  server/adaptors/integrations/repository/integration_reader.ts
Labels: integrations, maintenance

#2379 Add release notes for 3.0.0-aplha1
  release-notes/opensearch-observability.release-notes-3.0.0.0-alpha1.md
Labels: maintenance

#2375 Support custom logs correlation
  common/constants/trace_analytics.ts
  common/types/trace_analytics.ts
  public/components/event_analytics/explorer/explorer.tsx
  public/components/trace_analytics/components/common/__tests__/custom_index_flyout.test.tsx
  public/components/trace_analytics/components/common/custom_index_flyout.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/home.tsx
  server/plugin_helper/register_settings.ts
Labels: enhancement, backport 2.x

#2383 Service Content/View Optimizations
  public/components/application_analytics/components/flyout_components/service_detail_flyout.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/traces/span_detail_panel.tsx
  public/components/trace_analytics/requests/services_request_handler.ts
Labels: backport 2.x, maintenance

#2389 Bump dep serialize-javascript version to 6.0.2 and @babel/runtime to 7.26.10
  package.json
  yarn.lock
Labels: enhancement, backport 2.x, backport 2.19

#2388 Minor CI updates and workflow fixes
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/link-checker.yml
  .github/workflows/lint.yml
  .github/workflows/verify-binary-install.yml
Labels: maintenance

#2392 Services to Traces - Flyout redirection
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  public/components/trace_analytics/components/services/service_view.tsx
Labels: bug, backport 2.x

#2394 Update README.md
  public/components/getting_started/getting_started_artifacts/otel-services/README.md
Labels: maintenance

#2387 Improve error handling when setting up and reading a new integration
  server/adaptors/integrations/repository/integration_reader.ts
  server/adaptors/integrations/repository/utils.ts
Labels: integrations, infrastructure

#2395 Event Analytics - Cypress flaky fix
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/integration/event_analytics_test/event_analytics.spec.js
  .cypress/utils/event_analytics/helpers.js
Labels: bug
