Repository opensearch-project/dashboards-observability, pull requests merged in 2025-05, with the labels that each got.

#2437 Traces - Custom Traces mode pagination reset
  public/components/trace_analytics/components/traces/traces_content.tsx
Labels: bug, backport 3.0

#2438 Release Notes 3.0.0
  release-notes/opensearch-observability.release-notes-3.0.0.0.md
Labels: enhancement

#2435 Traces - Add traces unique count based on cardinality aggregation
  public/components/trace_analytics/components/common/constants.tsx
  public/components/trace_analytics/components/common/shared_components/component_helper_functions.tsx
  public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
  public/components/trace_analytics/requests/queries/traces_queries.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: maintenance
