Repository opensearch-project/dashboards-observability, pull requests merged in 2025-04, with the labels that each got.

#2390 Traces - Custom source switch to data grid
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/shared_components/component_helper_functions.tsx
  public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx
  public/components/trace_analytics/components/common/shared_components/sharedComponents.scss
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/span_detail_table.test.tsx
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/trace_table_helpers.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx
  public/components/trace_analytics/index.scss
  public/components/trace_analytics/requests/queries/traces_queries.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: enhancement, backport 2.x

#2398 Trace to logs correlation, action icon updates
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  common/constants/trace_analytics.ts
  common/types/trace_analytics.ts
  public/components/trace_analytics/components/common/__tests__/custom_index_flyout.test.tsx
  public/components/trace_analytics/components/common/__tests__/redirection_helpers.test.tsx
  public/components/trace_analytics/components/common/custom_index_flyout.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/common/plots/service_map.tsx
  public/components/trace_analytics/components/common/redirection_helpers.tsx
  public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap
  public/components/trace_analytics/components/dashboard/mode_picker.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/services/services_content.tsx
  public/components/trace_analytics/components/services/services_table.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_flyout.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/span_detail_flyout.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
  public/components/trace_analytics/index.scss
  server/plugin_helper/register_settings.ts
Labels: enhancement

#2397 Custom Traces- Sorting/Toast
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: bug

#2399 Traces table fix for invalid date
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/traces_table.tsx
  public/components/trace_analytics/requests/queries/traces_queries.ts
Labels: bug

#2401 Bump dashboards observability to version 3.0.0.0-beta1
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-dashboards-observability-test.yml
  .github/workflows/integration-tests-workflow.yml
  .github/workflows/verify-binary-install.yml
  opensearch_dashboards.json
  package.json
Labels: maintenance

#2403 Traces - Update custom source display, add toast.
  public/components/trace_analytics/components/common/shared_components/component_helper_functions.tsx
  public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx
  public/components/trace_analytics/requests/__tests__/helper_funtions.test.tsx
  public/components/trace_analytics/requests/helper_functions.tsx
  public/components/trace_analytics/requests/queries/traces_queries.ts
  public/components/trace_analytics/requests/request_handler.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
  server/routes/trace_analytics_dsl_router.ts
Labels: maintenance

#2402 Application Analytics - Flaky cypress fix
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/utils/app_constants.js
Labels: bug

#2404 [CVE] Issue/CVE fix CVE 2024 53382
  package.json
  yarn.lock
Labels: Mend: dependency security vulnerability, maintenance

#2405 [Cypress] Upgrade cypress version to ^13.6.0
  .github/workflows/integration-tests-workflow.yml
  package.json
  yarn.lock
Labels: maintenance

#2400 Adding husky `.only` check hook to test files
  .husky/hooks/check-test-only.sh
  package.json
Labels: maintenance

#2406 Remove support for legacy notebooks
  public/components/notebooks/components/main.tsx
  server/adaptors/notebooks/default_backend.ts
  server/adaptors/notebooks/index.ts
  server/adaptors/notebooks/notebook_adaptor.ts
  server/routes/notebooks/noteRouter.ts
  server/routes/notebooks/paraRouter.ts
Labels: enhancement

#2409 Release notes for 3.0.0.0-beta1
  release-notes/opensearch-observability.release-notes-3.0.0.0-beta1.md
Labels: release, maintenance

#2408 Cypress - Config fix
  .cypress/integration/event_analytics_test/event_analytics.spec.js
  .cypress/integration/integrations_test/integrations.spec.js
  .cypress/integration/metrics_analytics_test/metrics_analytics.spec.js
  .cypress/integration/panels_test/panels.spec.ts
  .cypress/integration/trace_analytics_test/trace_analytics_dashboard.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/support/index.js
  .cypress/utils/constants.js
  .cypress/utils/event_analytics/helpers.js
  cypress.config.js
Labels: bug

#2410 Adding Amazon Network Firewall Integration
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/.DS_Store
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/amazon_networkfirewall-1.0.0.json
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/amazon_networkfirewall-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/amazon_networkfirewall_aggregated-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/create_mv-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/create_mv_aggregated-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/create_skipping_index-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/create_table-1.0.0.sql
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/assets/example_queries-1.0.0.ndjson
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/data/sample.json
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/info/README.md
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/schemas/amazon_networkfirewall-1.0.0.mapping.json
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/schemas/cloud-1.0.0.mapping.json
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/schemas/logs_amazon_networkfirewall-1.0.0.mapping.json
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/static/dashboard.png
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/static/dashboard1.png
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/static/dashboard2.png
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/static/dashboard3.png
  server/adaptors/integrations/__data__/repository/amazon_networkfirewall/static/logo.svg
Labels: enhancement, integrations

#2413 Fix link checker 404 and update the table of content in README
  README.md
Labels: documentation, maintenance

#2407 Traces - Update custom source toast/error/sorting
  .cypress/integration/app_analytics_test/app_analytics.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js
  .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
  .cypress/utils/constants.js
  public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap
  public/components/application_analytics/components/flyout_components/trace_detail_render.tsx
  public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap
  public/components/trace_analytics/components/common/search_bar.tsx
  public/components/trace_analytics/components/common/shared_components/component_helper_functions.tsx
  public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/services/service_view.tsx
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap
  public/components/trace_analytics/components/traces/span_detail_table.tsx
  public/components/trace_analytics/components/traces/trace_table_helpers.tsx
  public/components/trace_analytics/components/traces/trace_view.tsx
  public/components/trace_analytics/components/traces/traces_content.tsx
  public/components/trace_analytics/components/traces/traces_table.tsx
  public/components/trace_analytics/requests/queries/services_queries.ts
  public/components/trace_analytics/requests/queries/traces_queries.ts
  public/components/trace_analytics/requests/services_request_handler.ts
  public/components/trace_analytics/requests/traces_request_handler.ts
Labels: bug

#2412 [Doc] Update the integraiton SOP's publish section
  docs/integrations/setup.md
Labels: documentation, integrations

#2418 [Bug] Notebooks - Action popover
  public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap
  public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap
  public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap
  public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap
  public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap
  public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
  public/components/notebooks/components/paragraph_components/paragraphs.tsx
  public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap
  public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap
  public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
Labels: bug, backport 3.0

#2417 [Bug] Notebooks - fix set_paragraphs API
  server/routes/notebooks/paraRouter.ts
Labels: bug, backport 3.0

#2431 release notes for 2.19.2
  release-notes/opensearch-observability.release-notes-2.19.2.0.md
Labels: v2.19.2

#2432 Traces - Add "attributes" field
  public/components/trace_analytics/components/common/__tests__/helper_functions.test.tsx
  public/components/trace_analytics/components/common/helper_functions.tsx
  public/components/trace_analytics/components/traces/trace_table_helpers.tsx
  public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx
  test/constants.ts
Labels: maintenance, backport 3.0
